/* fading-label.c generated by valac 0.22.1, the Vala compiler
 * generated from fading-label.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: nil; tab-width: 4 -*-
 *
 * Copyright (C) 2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Michael Terry <michael.terry@canonical.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <float.h>
#include <math.h>


#define TYPE_FADING_LABEL (fading_label_get_type ())
#define FADING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FADING_LABEL, FadingLabel))
#define FADING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FADING_LABEL, FadingLabelClass))
#define IS_FADING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FADING_LABEL))
#define IS_FADING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FADING_LABEL))
#define FADING_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FADING_LABEL, FadingLabelClass))

typedef struct _FadingLabel FadingLabel;
typedef struct _FadingLabelClass FadingLabelClass;
typedef struct _FadingLabelPrivate FadingLabelPrivate;
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _cairo_pattern_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_pattern_destroy (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

struct _FadingLabel {
	GtkLabel parent_instance;
	FadingLabelPrivate * priv;
};

struct _FadingLabelClass {
	GtkLabelClass parent_class;
};

struct _FadingLabelPrivate {
	cairo_surface_t* cached_surface;
};


static gpointer fading_label_parent_class = NULL;

GType fading_label_get_type (void) G_GNUC_CONST;
#define FADING_LABEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_FADING_LABEL, FadingLabelPrivate))
enum  {
	FADING_LABEL_DUMMY_PROPERTY
};
FadingLabel* fading_label_new (const gchar* text);
FadingLabel* fading_label_construct (GType object_type, const gchar* text);
static void fading_label_real_get_preferred_width (GtkWidget* base, gint* minimum, gint* natural);
static void fading_label_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum, gint* natural);
static void fading_label_real_size_allocate (GtkWidget* base, GtkAllocation* allocation);
static cairo_surface_t* fading_label_make_surface (FadingLabel* self, cairo_t* orig_c);
static gboolean fading_label_real_draw (GtkWidget* base, cairo_t* c);
static void fading_label_finalize (GObject* obj);


FadingLabel* fading_label_construct (GType object_type, const gchar* text) {
	FadingLabel * self = NULL;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (text != NULL, NULL);
	_tmp0_ = text;
	self = (FadingLabel*) g_object_new (object_type, "label", _tmp0_, NULL);
	return self;
}


FadingLabel* fading_label_new (const gchar* text) {
	return fading_label_construct (TYPE_FADING_LABEL, text);
}


static void fading_label_real_get_preferred_width (GtkWidget* base, gint* minimum, gint* natural) {
	FadingLabel * self;
	gint _vala_minimum = 0;
	gint _vala_natural = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	self = (FadingLabel*) base;
	GTK_WIDGET_CLASS (fading_label_parent_class)->get_preferred_width ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_LABEL, GtkLabel), &_tmp0_, &_tmp1_);
	_vala_minimum = _tmp0_;
	_vala_natural = _tmp1_;
	_vala_minimum = 0;
	if (minimum) {
		*minimum = _vala_minimum;
	}
	if (natural) {
		*natural = _vala_natural;
	}
}


static void fading_label_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum, gint* natural) {
	FadingLabel * self;
	gint _vala_minimum = 0;
	gint _vala_natural = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	self = (FadingLabel*) base;
	_tmp0_ = height;
	GTK_WIDGET_CLASS (fading_label_parent_class)->get_preferred_width_for_height ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_LABEL, GtkLabel), _tmp0_, &_tmp1_, &_tmp2_);
	_vala_minimum = _tmp1_;
	_vala_natural = _tmp2_;
	_vala_minimum = 0;
	if (minimum) {
		*minimum = _vala_minimum;
	}
	if (natural) {
		*natural = _vala_natural;
	}
}


static void fading_label_real_size_allocate (GtkWidget* base, GtkAllocation* allocation) {
	FadingLabel * self;
	GtkAllocation _tmp0_ = {0};
	self = (FadingLabel*) base;
	g_return_if_fail (allocation != NULL);
	_tmp0_ = *allocation;
	GTK_WIDGET_CLASS (fading_label_parent_class)->size_allocate ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_LABEL, GtkLabel), &_tmp0_);
	_cairo_surface_destroy0 (self->priv->cached_surface);
	self->priv->cached_surface = NULL;
}


static cairo_surface_t* fading_label_make_surface (FadingLabel* self, cairo_t* orig_c) {
	cairo_surface_t* result = NULL;
	gint w = 0;
	gint h = 0;
	PangoLayout* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint bw = 0;
	gint _tmp3_ = 0;
	gint bh = 0;
	gint _tmp4_ = 0;
	cairo_surface_t* surface = NULL;
	cairo_t* _tmp5_ = NULL;
	cairo_surface_t* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	cairo_surface_t* _tmp9_ = NULL;
	cairo_t* c = NULL;
	cairo_surface_t* _tmp10_ = NULL;
	cairo_t* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (orig_c != NULL, NULL);
	_tmp0_ = gtk_label_get_layout ((GtkLabel*) self);
	pango_layout_get_pixel_size (_tmp0_, &_tmp1_, &_tmp2_);
	w = _tmp1_;
	h = _tmp2_;
	_tmp3_ = gtk_widget_get_allocated_width ((GtkWidget*) self);
	bw = _tmp3_;
	_tmp4_ = gtk_widget_get_allocated_height ((GtkWidget*) self);
	bh = _tmp4_;
	_tmp5_ = orig_c;
	_tmp6_ = cairo_get_target (_tmp5_);
	_tmp7_ = bw;
	_tmp8_ = bh;
	_tmp9_ = cairo_surface_create_similar (_tmp6_, CAIRO_CONTENT_COLOR_ALPHA, _tmp7_, _tmp8_);
	surface = _tmp9_;
	_tmp10_ = surface;
	_tmp11_ = cairo_create (_tmp10_);
	c = _tmp11_;
	_tmp12_ = w;
	_tmp13_ = bw;
	if (_tmp12_ > _tmp13_) {
		cairo_t* _tmp14_ = NULL;
		cairo_t* _tmp15_ = NULL;
		cairo_t* _tmp16_ = NULL;
		cairo_pattern_t* mask = NULL;
		gint _tmp17_ = 0;
		cairo_pattern_t* _tmp18_ = NULL;
		cairo_pattern_t* _tmp19_ = NULL;
		gint _tmp20_ = 0;
		cairo_pattern_t* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		cairo_pattern_t* _tmp23_ = NULL;
		cairo_t* _tmp24_ = NULL;
		cairo_pattern_t* _tmp25_ = NULL;
		_tmp14_ = c;
		cairo_push_group (_tmp14_);
		_tmp15_ = c;
		GTK_WIDGET_CLASS (fading_label_parent_class)->draw ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_LABEL, GtkLabel), _tmp15_);
		_tmp16_ = c;
		cairo_pop_group_to_source (_tmp16_);
		_tmp17_ = bw;
		_tmp18_ = cairo_pattern_create_linear ((gdouble) 0, (gdouble) 0, (gdouble) _tmp17_, (gdouble) 0);
		mask = _tmp18_;
		_tmp19_ = mask;
		_tmp20_ = bw;
		cairo_pattern_add_color_stop_rgba (_tmp19_, 1.0 - (27.0 / _tmp20_), 1.0, 1.0, 1.0, 1.0);
		_tmp21_ = mask;
		_tmp22_ = bw;
		cairo_pattern_add_color_stop_rgba (_tmp21_, 1.0 - (21.6 / _tmp22_), 1.0, 1.0, 1.0, 0.5);
		_tmp23_ = mask;
		cairo_pattern_add_color_stop_rgba (_tmp23_, 1.0, 1.0, 1.0, 1.0, 0.0);
		_tmp24_ = c;
		_tmp25_ = mask;
		cairo_mask (_tmp24_, _tmp25_);
		_cairo_pattern_destroy0 (mask);
	} else {
		cairo_t* _tmp26_ = NULL;
		_tmp26_ = c;
		GTK_WIDGET_CLASS (fading_label_parent_class)->draw ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_LABEL, GtkLabel), _tmp26_);
	}
	result = surface;
	_cairo_destroy0 (c);
	return result;
}


static gboolean fading_label_real_draw (GtkWidget* base, cairo_t* c) {
	FadingLabel * self;
	gboolean result = FALSE;
	cairo_surface_t* _tmp0_ = NULL;
	cairo_t* _tmp3_ = NULL;
	cairo_surface_t* _tmp4_ = NULL;
	cairo_t* _tmp5_ = NULL;
	self = (FadingLabel*) base;
	g_return_val_if_fail (c != NULL, FALSE);
	_tmp0_ = self->priv->cached_surface;
	if (_tmp0_ == NULL) {
		cairo_t* _tmp1_ = NULL;
		cairo_surface_t* _tmp2_ = NULL;
		_tmp1_ = c;
		_tmp2_ = fading_label_make_surface (self, _tmp1_);
		_cairo_surface_destroy0 (self->priv->cached_surface);
		self->priv->cached_surface = _tmp2_;
	}
	_tmp3_ = c;
	_tmp4_ = self->priv->cached_surface;
	cairo_set_source_surface (_tmp3_, _tmp4_, (gdouble) 0, (gdouble) 0);
	_tmp5_ = c;
	cairo_paint (_tmp5_);
	result = FALSE;
	return result;
}


static void fading_label_class_init (FadingLabelClass * klass) {
	fading_label_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FadingLabelPrivate));
	GTK_WIDGET_CLASS (klass)->get_preferred_width = fading_label_real_get_preferred_width;
	GTK_WIDGET_CLASS (klass)->get_preferred_width_for_height = fading_label_real_get_preferred_width_for_height;
	GTK_WIDGET_CLASS (klass)->size_allocate = fading_label_real_size_allocate;
	GTK_WIDGET_CLASS (klass)->draw = fading_label_real_draw;
	G_OBJECT_CLASS (klass)->finalize = fading_label_finalize;
}


static void fading_label_instance_init (FadingLabel * self) {
	self->priv = FADING_LABEL_GET_PRIVATE (self);
}


static void fading_label_finalize (GObject* obj) {
	FadingLabel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_FADING_LABEL, FadingLabel);
	_cairo_surface_destroy0 (self->priv->cached_surface);
	G_OBJECT_CLASS (fading_label_parent_class)->finalize (obj);
}


GType fading_label_get_type (void) {
	static volatile gsize fading_label_type_id__volatile = 0;
	if (g_once_init_enter (&fading_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FadingLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fading_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FadingLabel), 0, (GInstanceInitFunc) fading_label_instance_init, NULL };
		GType fading_label_type_id;
		fading_label_type_id = g_type_register_static (GTK_TYPE_LABEL, "FadingLabel", &g_define_type_info, 0);
		g_once_init_leave (&fading_label_type_id__volatile, fading_label_type_id);
	}
	return fading_label_type_id__volatile;
}



