/* logo-generator.c generated by valac 0.22.1, the Vala compiler
 * generated from logo-generator.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include <pango/pango.h>
#include <pango/pangocairo.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_PangoFontDescription_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoFontDescription_free (var), NULL)))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};


static gpointer main_parent_class = NULL;
static gchar* main_file;
static gchar* main_file = NULL;
static gchar* main_text;
static gchar* main_text = NULL;
static gchar* main_result;
static gchar* main_result = NULL;

GType main_get_type (void) G_GNUC_CONST;
enum  {
	MAIN_DUMMY_PROPERTY
};
gint main_main (gchar** args, int args_length1);
static void _vala_PangoFontDescription_free (PangoFontDescription* self);
Main* main_new (void);
Main* main_construct (GType object_type);
static void main_finalize (GObject* obj);

static const GOptionEntry MAIN_options[4] = {{"logo", (gchar) 0, 0, G_OPTION_ARG_FILENAME, &main_file, "Path to logo", "LOGO"}, {"text", (gchar) 0, 0, G_OPTION_ARG_STRING, &main_text, "Sublogo text", "TEXT"}, {"output", (gchar) 0, 0, G_OPTION_ARG_FILENAME, &main_result, "Path to rendered output", "OUTPUT"}, {NULL}};

static void _vala_PangoFontDescription_free (PangoFontDescription* self) {
	g_boxed_free (pango_font_description_get_type (), self);
}


gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	cairo_surface_t* surface = NULL;
	cairo_surface_t* _tmp10_ = NULL;
	cairo_t* context = NULL;
	cairo_surface_t* _tmp11_ = NULL;
	cairo_t* _tmp12_ = NULL;
	cairo_t* _tmp13_ = NULL;
	cairo_surface_t* logo = NULL;
	const gchar* _tmp14_ = NULL;
	cairo_surface_t* _tmp15_ = NULL;
	cairo_t* _tmp16_ = NULL;
	cairo_surface_t* _tmp17_ = NULL;
	cairo_t* _tmp18_ = NULL;
	cairo_t* _tmp19_ = NULL;
	cairo_t* _tmp20_ = NULL;
	cairo_surface_t* _tmp21_ = NULL;
	gint _tmp22_ = 0;
	cairo_surface_t* _tmp23_ = NULL;
	gint _tmp24_ = 0;
	cairo_surface_t* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	PangoFontDescription* font_description = NULL;
	PangoFontDescription* _tmp27_ = NULL;
	PangoFontDescription* _tmp28_ = NULL;
	PangoFontDescription* _tmp29_ = NULL;
	cairo_surface_t* _tmp30_ = NULL;
	gint _tmp31_ = 0;
	PangoLayout* layout = NULL;
	cairo_t* _tmp32_ = NULL;
	PangoLayout* _tmp33_ = NULL;
	PangoLayout* _tmp34_ = NULL;
	PangoFontDescription* _tmp35_ = NULL;
	PangoLayout* _tmp36_ = NULL;
	const gchar* _tmp37_ = NULL;
	cairo_t* _tmp38_ = NULL;
	PangoLayout* _tmp39_ = NULL;
	PangoLayoutLine* _tmp40_ = NULL;
	cairo_surface_t* _tmp41_ = NULL;
	const gchar* _tmp42_ = NULL;
	GError * _inner_error_ = NULL;
	{
		GOptionContext* opt_context = NULL;
		GOptionContext* _tmp0_ = NULL;
		GOptionContext* _tmp1_ = NULL;
		GOptionContext* _tmp2_ = NULL;
		GOptionContext* _tmp3_ = NULL;
		_tmp0_ = g_option_context_new ("- OptionContext example");
		opt_context = _tmp0_;
		_tmp1_ = opt_context;
		g_option_context_set_help_enabled (_tmp1_, TRUE);
		_tmp2_ = opt_context;
		g_option_context_add_main_entries (_tmp2_, MAIN_options, NULL);
		_tmp3_ = opt_context;
		g_option_context_parse (_tmp3_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt_context);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch0_g_option_error;
			}
			_g_option_context_free0 (opt_context);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_g_option_context_free0 (opt_context);
	}
	goto __finally0;
	__catch0_g_option_error:
	{
		GError* e = NULL;
		FILE* _tmp4_ = NULL;
		GError* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		FILE* _tmp7_ = NULL;
		gchar** _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		const gchar* _tmp9_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stdout;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "error: %s\n", _tmp6_);
		_tmp7_ = stdout;
		_tmp8_ = args;
		_tmp8__length1 = args_length1;
		_tmp9_ = _tmp8_[0];
		fprintf (_tmp7_, "Run '%s --help' to see a full list of available command line options.\n", _tmp9_);
		result = 0;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_tmp10_ = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 245, 43);
	surface = _tmp10_;
	_tmp11_ = surface;
	_tmp12_ = cairo_create (_tmp11_);
	context = _tmp12_;
	_tmp13_ = context;
	cairo_translate (_tmp13_, (gdouble) 42, (gdouble) 11);
	_tmp14_ = main_file;
	_tmp15_ = cairo_image_surface_create_from_png (_tmp14_);
	logo = _tmp15_;
	_tmp16_ = context;
	_tmp17_ = logo;
	cairo_set_source_surface (_tmp16_, _tmp17_, (gdouble) 0, (gdouble) 0);
	_tmp18_ = context;
	cairo_paint (_tmp18_);
	_tmp19_ = context;
	cairo_set_source_rgba (_tmp19_, (gdouble) 1, (gdouble) 1, (gdouble) 1, (gdouble) 1);
	_tmp20_ = context;
	_tmp21_ = logo;
	_tmp22_ = cairo_image_surface_get_width (_tmp21_);
	_tmp23_ = logo;
	_tmp24_ = cairo_image_surface_get_height (_tmp23_);
	_tmp25_ = logo;
	_tmp26_ = cairo_image_surface_get_height (_tmp25_);
	cairo_translate (_tmp20_, _tmp22_ + (0.25 * _tmp24_), (gdouble) _tmp26_);
	_tmp27_ = pango_font_description_new ();
	font_description = _tmp27_;
	_tmp28_ = font_description;
	pango_font_description_set_family (_tmp28_, "Ubuntu");
	_tmp29_ = font_description;
	_tmp30_ = logo;
	_tmp31_ = cairo_image_surface_get_height (_tmp30_);
	pango_font_description_set_size (_tmp29_, (gint) ((0.75 * _tmp31_) * PANGO_SCALE));
	_tmp32_ = context;
	_tmp33_ = pango_cairo_create_layout (_tmp32_);
	layout = _tmp33_;
	_tmp34_ = layout;
	_tmp35_ = font_description;
	pango_layout_set_font_description (_tmp34_, _tmp35_);
	_tmp36_ = layout;
	_tmp37_ = main_text;
	pango_layout_set_text (_tmp36_, _tmp37_, -1);
	_tmp38_ = context;
	_tmp39_ = layout;
	_tmp40_ = pango_layout_get_line (_tmp39_, 0);
	pango_cairo_show_layout_line (_tmp38_, _tmp40_);
	_tmp41_ = surface;
	_tmp42_ = main_result;
	cairo_surface_write_to_png (_tmp41_, _tmp42_);
	result = 0;
	_g_object_unref0 (layout);
	__vala_PangoFontDescription_free0 (font_description);
	_cairo_surface_destroy0 (logo);
	_cairo_destroy0 (context);
	_cairo_surface_destroy0 (surface);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return main_main (argv, argc);
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	self = (Main*) g_object_new (object_type, NULL);
	return self;
}


Main* main_new (void) {
	return main_construct (TYPE_MAIN);
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
}


static void main_instance_init (Main * self) {
}


static void main_finalize (GObject* obj) {
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}



