/* main-window.c generated by valac 0.22.1, the Vala compiler
 * generated from main-window.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: nil; tab-width: 4 -*-
 *
 * Copyright (C) 2011,2012 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Robert Ancell <robert.ancell@canonical.com>
 *          Michael Terry <michael.terry@canonical.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gtk/gtkx.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/Xregion.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <atk/atk.h>
#include <glib/gi18n-lib.h>
#include "config.h"


#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
typedef struct _MainWindowPrivate MainWindowPrivate;

#define TYPE_LIST_STACK (list_stack_get_type ())
#define LIST_STACK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LIST_STACK, ListStack))
#define LIST_STACK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LIST_STACK, ListStackClass))
#define IS_LIST_STACK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LIST_STACK))
#define IS_LIST_STACK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LIST_STACK))
#define LIST_STACK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LIST_STACK, ListStackClass))

typedef struct _ListStack ListStack;
typedef struct _ListStackClass ListStackClass;

#define TYPE_MONITOR (monitor_get_type ())
#define MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MONITOR, Monitor))
#define MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MONITOR, MonitorClass))
#define IS_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MONITOR))
#define IS_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MONITOR))
#define MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MONITOR, MonitorClass))

typedef struct _Monitor Monitor;
typedef struct _MonitorClass MonitorClass;

#define TYPE_BACKGROUND (background_get_type ())
#define BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BACKGROUND, Background))
#define BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BACKGROUND, BackgroundClass))
#define IS_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BACKGROUND))
#define IS_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BACKGROUND))
#define BACKGROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BACKGROUND, BackgroundClass))

typedef struct _Background Background;
typedef struct _BackgroundClass BackgroundClass;

#define TYPE_SHUTDOWN_DIALOG (shutdown_dialog_get_type ())
#define SHUTDOWN_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SHUTDOWN_DIALOG, ShutdownDialog))
#define SHUTDOWN_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SHUTDOWN_DIALOG, ShutdownDialogClass))
#define IS_SHUTDOWN_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SHUTDOWN_DIALOG))
#define IS_SHUTDOWN_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SHUTDOWN_DIALOG))
#define SHUTDOWN_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SHUTDOWN_DIALOG, ShutdownDialogClass))

typedef struct _ShutdownDialog ShutdownDialog;
typedef struct _ShutdownDialogClass ShutdownDialogClass;
#define __g_list_free__monitor_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__monitor_unref0_ (var), NULL)))
#define _monitor_unref0(var) ((var == NULL) ? NULL : (var = (monitor_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_FADABLE_BOX (fadable_box_get_type ())
#define FADABLE_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FADABLE_BOX, FadableBox))
#define FADABLE_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FADABLE_BOX, FadableBoxClass))
#define IS_FADABLE_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FADABLE_BOX))
#define IS_FADABLE_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FADABLE_BOX))
#define FADABLE_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FADABLE_BOX, FadableBoxClass))

typedef struct _FadableBox FadableBox;
typedef struct _FadableBoxClass FadableBoxClass;

#define TYPE_GREETER_LIST (greeter_list_get_type ())
#define GREETER_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GREETER_LIST, GreeterList))
#define GREETER_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GREETER_LIST, GreeterListClass))
#define IS_GREETER_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GREETER_LIST))
#define IS_GREETER_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GREETER_LIST))
#define GREETER_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GREETER_LIST, GreeterListClass))

typedef struct _GreeterList GreeterList;
typedef struct _GreeterListClass GreeterListClass;

#define TYPE_SHUTDOWN_DIALOG_TYPE (shutdown_dialog_type_get_type ())
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _MonitorPrivate MonitorPrivate;

#define TYPE_USER_LIST (user_list_get_type ())
#define USER_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_LIST, UserList))
#define USER_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_USER_LIST, UserListClass))
#define IS_USER_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_LIST))
#define IS_USER_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_USER_LIST))
#define USER_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_LIST, UserListClass))

typedef struct _UserList UserList;
typedef struct _UserListClass UserListClass;

#define GREETER_LIST_TYPE_SCROLL_TARGET (greeter_list_scroll_target_get_type ())

#define TYPE_UNITY_GREETER (unity_greeter_get_type ())
#define UNITY_GREETER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UNITY_GREETER, UnityGreeter))
#define UNITY_GREETER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UNITY_GREETER, UnityGreeterClass))
#define IS_UNITY_GREETER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UNITY_GREETER))
#define IS_UNITY_GREETER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UNITY_GREETER))
#define UNITY_GREETER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UNITY_GREETER, UnityGreeterClass))

typedef struct _UnityGreeter UnityGreeter;
typedef struct _UnityGreeterClass UnityGreeterClass;
typedef struct _UnityGreeterPrivate UnityGreeterPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

#define TYPE_FLAT_BUTTON (flat_button_get_type ())
#define FLAT_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FLAT_BUTTON, FlatButton))
#define FLAT_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FLAT_BUTTON, FlatButtonClass))
#define IS_FLAT_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FLAT_BUTTON))
#define IS_FLAT_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FLAT_BUTTON))
#define FLAT_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FLAT_BUTTON, FlatButtonClass))

typedef struct _FlatButton FlatButton;
typedef struct _FlatButtonClass FlatButtonClass;

struct _MainWindow {
	GtkWindow parent_instance;
	MainWindowPrivate * priv;
	ListStack* stack;
};

struct _MainWindowClass {
	GtkWindowClass parent_class;
};

struct _MainWindowPrivate {
	GList* monitors;
	Monitor* primary_monitor;
	Monitor* active_monitor;
	Background* background;
	GtkBox* login_box;
	GtkBox* hbox;
	GtkButton* back_button;
	ShutdownDialog* shutdown_dialog;
	GtkWindow* _keyboard_window;
	GPid keyboard_pid;
	GtkButton* shutdownbutton;
	GtkToggleButton* a11ybutton;
};

typedef enum  {
	SHUTDOWN_DIALOG_TYPE_LOGOUT,
	SHUTDOWN_DIALOG_TYPE_SHUTDOWN,
	SHUTDOWN_DIALOG_TYPE_RESTART
} ShutdownDialogType;

struct _Monitor {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MonitorPrivate * priv;
	gint x;
	gint y;
	gint width;
	gint height;
};

struct _MonitorClass {
	GTypeClass parent_class;
	void (*finalize) (Monitor *self);
};

typedef enum  {
	GREETER_LIST_SCROLL_TARGET_START,
	GREETER_LIST_SCROLL_TARGET_END,
	GREETER_LIST_SCROLL_TARGET_UP,
	GREETER_LIST_SCROLL_TARGET_DOWN
} GreeterListScrollTarget;

struct _UnityGreeter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	UnityGreeterPrivate * priv;
	gboolean test_mode;
	gboolean orca_needs_kick;
};

struct _UnityGreeterClass {
	GTypeClass parent_class;
	void (*finalize) (UnityGreeter *self);
};


static gpointer main_window_parent_class = NULL;
extern UnityGreeter* unity_greeter_singleton;

GType main_window_get_type (void) G_GNUC_CONST;
GType list_stack_get_type (void) G_GNUC_CONST;
gpointer monitor_ref (gpointer instance);
void monitor_unref (gpointer instance);
GParamSpec* param_spec_monitor (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_monitor (GValue* value, gpointer v_object);
void value_take_monitor (GValue* value, gpointer v_object);
gpointer value_get_monitor (const GValue* value);
GType monitor_get_type (void) G_GNUC_CONST;
GType background_get_type (void) G_GNUC_CONST;
GType shutdown_dialog_get_type (void) G_GNUC_CONST;
#define MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN_WINDOW, MainWindowPrivate))
enum  {
	MAIN_WINDOW_DUMMY_PROPERTY,
	MAIN_WINDOW_KEYBOARD_WINDOW
};
static void _monitor_unref0_ (gpointer var);
static void _g_list_free__monitor_unref0_ (GList* self);
#define MAIN_WINDOW_BUTTONBOX_HEIGHT 80
GType fadable_box_get_type (void) G_GNUC_CONST;
GType greeter_list_get_type (void) G_GNUC_CONST;
void main_window_push_list (MainWindow* self, GreeterList* widget);
void list_stack_push (ListStack* self, GreeterList* pushed);
guint list_stack_get_num_children (ListStack* self);
void main_window_pop_list (MainWindow* self);
void list_stack_pop (ListStack* self);
static void main_window_real_size_allocate (GtkWidget* base, GtkAllocation* allocation);
gint get_grid_offset (gint size);
#define grid_size 40
static void main_window_shutdownbutton_clicked_cb (MainWindow* self, GtkButton* button);
GType shutdown_dialog_type_get_type (void) G_GNUC_CONST;
void main_window_show_shutdown_dialog (MainWindow* self, ShutdownDialogType type);
static void main_window_keyboardbutton_clicked_cb (MainWindow* self, GtkToggleButton* button);
gboolean ug_settings_set_boolean (const gchar* key, gboolean value);
#define UG_SETTINGS_KEY_ONSCREEN_KEYBOARD "onscreen-keyboard"
GtkWindow* main_window_get_keyboard_window (MainWindow* self);
static void main_window_set_keyboard_window (MainWindow* self, GtkWindow* value);
static void main_window_monitors_changed_cb (MainWindow* self, GdkScreen* screen);
static gboolean main_window_monitor_is_unique_position (MainWindow* self, GdkScreen* screen, gint n);
Monitor* monitor_new (gint x, gint y, gint width, gint height);
Monitor* monitor_construct (GType object_type, gint x, gint y, gint width, gint height);
void background_set_monitors (Background* self, GList* monitors);
static void main_window_move_to_monitor (MainWindow* self, Monitor* monitor);
static gboolean main_window_real_motion_notify_event (GtkWidget* base, GdkEventMotion* event);
void background_set_active_monitor (Background* self, Monitor* monitor);
void shutdown_dialog_set_active_monitor (ShutdownDialog* self, Monitor* m);
static void main_window_add_user_list (MainWindow* self);
UserList* user_list_new (Background* bg);
UserList* user_list_construct (GType object_type, Background* bg);
GType user_list_get_type (void) G_GNUC_CONST;
void unity_greeter_add_style_class (GtkWidget* widget);
static gboolean main_window_real_key_press_event (GtkWidget* base, GdkEventKey* event);
GreeterList* list_stack_top (ListStack* self);
gboolean user_list_get_show_hidden_users (UserList* self);
void user_list_set_show_hidden_users (UserList* self, gboolean value);
void greeter_list_cancel_authentication (GreeterList* self);
void shutdown_dialog_cancel (ShutdownDialog* self);
GType greeter_list_scroll_target_get_type (void) G_GNUC_CONST;
void greeter_list_scroll (GreeterList* self, GreeterListScrollTarget target);
void shutdown_dialog_focus_prev (ShutdownDialog* self);
void shutdown_dialog_focus_next (ShutdownDialog* self);
gpointer unity_greeter_ref (gpointer instance);
void unity_greeter_unref (gpointer instance);
GParamSpec* param_spec_unity_greeter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_unity_greeter (GValue* value, gpointer v_object);
void value_take_unity_greeter (GValue* value, gpointer v_object);
gpointer value_get_unity_greeter (const GValue* value);
GType unity_greeter_get_type (void) G_GNUC_CONST;
void main_window_set_keyboard_state (MainWindow* self);
gboolean ug_settings_get_boolean (const gchar* key);
ShutdownDialog* shutdown_dialog_new (ShutdownDialogType type, Background* bg);
ShutdownDialog* shutdown_dialog_construct (GType object_type, ShutdownDialogType type, Background* bg);
void main_window_close_shutdown_dialog (MainWindow* self);
static void _main_window_close_shutdown_dialog_shutdown_dialog_closed (ShutdownDialog* _sender, gpointer self);
MainWindow* main_window_new (void);
MainWindow* main_window_construct (GType object_type);
static GObject * main_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
gchar* ug_settings_get_string (const gchar* key);
#define UG_SETTINGS_KEY_BACKGROUND_COLOR "background-color"
Background* background_new (cairo_surface_t* target_surface);
Background* background_construct (GType object_type, cairo_surface_t* target_surface);
#define UG_SETTINGS_KEY_DRAW_GRID "draw-grid"
void background_set_draw_grid (Background* self, gboolean value);
#define UG_SETTINGS_KEY_BACKGROUND "background"
void background_set_default_background (Background* self, const gchar* value);
void background_set_logo (Background* self, const gchar* version_logo, const gchar* background_logo);
#define UG_SETTINGS_KEY_LOGO "logo"
#define UG_SETTINGS_KEY_BACKGROUND_LOGO "background-logo"
static void _main_window_keyboardbutton_clicked_cb_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _main_window_shutdownbutton_clicked_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
FlatButton* flat_button_new (void);
FlatButton* flat_button_construct (GType object_type);
GType flat_button_get_type (void) G_GNUC_CONST;
#define GREETER_LIST_BORDER 4
static void _main_window_pop_list_gtk_button_clicked (GtkButton* _sender, gpointer self);
ListStack* list_stack_new (void);
ListStack* list_stack_construct (GType object_type);
static void _main_window_monitors_changed_cb_gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self);
static void main_window_finalize (GObject* obj);
static void _vala_main_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_main_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _monitor_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (monitor_unref (var), NULL));
}


static void _g_list_free__monitor_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _monitor_unref0_, NULL);
	g_list_free (self);
}


void main_window_push_list (MainWindow* self, GreeterList* widget) {
	ListStack* _tmp0_ = NULL;
	GreeterList* _tmp1_ = NULL;
	ListStack* _tmp2_ = NULL;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	_tmp0_ = self->stack;
	_tmp1_ = widget;
	list_stack_push (_tmp0_, _tmp1_);
	_tmp2_ = self->stack;
	_tmp3_ = list_stack_get_num_children (_tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_ > ((guint) 1)) {
		GtkButton* _tmp5_ = NULL;
		_tmp5_ = self->priv->back_button;
		gtk_widget_show ((GtkWidget*) _tmp5_);
	}
}


void main_window_pop_list (MainWindow* self) {
	ListStack* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	ListStack* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->stack;
	_tmp1_ = list_stack_get_num_children (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ <= ((guint) 2)) {
		GtkButton* _tmp3_ = NULL;
		_tmp3_ = self->priv->back_button;
		gtk_widget_hide ((GtkWidget*) _tmp3_);
	}
	_tmp4_ = self->stack;
	list_stack_pop (_tmp4_);
}


static void main_window_real_size_allocate (GtkWidget* base, GtkAllocation* allocation) {
	MainWindow * self;
	GtkAllocation _tmp0_ = {0};
	GtkBox* _tmp1_ = NULL;
	self = (MainWindow*) base;
	g_return_if_fail (allocation != NULL);
	_tmp0_ = *allocation;
	GTK_WIDGET_CLASS (main_window_parent_class)->size_allocate ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_WINDOW, GtkWindow), &_tmp0_);
	_tmp1_ = self->priv->hbox;
	if (_tmp1_ != NULL) {
		GtkBox* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		GtkBox* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		GtkBox* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		GtkBox* _tmp11_ = NULL;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
		_tmp2_ = self->priv->hbox;
		_tmp3_ = gtk_widget_get_allocated_width ((GtkWidget*) self);
		_tmp4_ = get_grid_offset (_tmp3_);
		gtk_widget_set_margin_left ((GtkWidget*) _tmp2_, _tmp4_ + grid_size);
		_tmp5_ = self->priv->hbox;
		_tmp6_ = gtk_widget_get_allocated_width ((GtkWidget*) self);
		_tmp7_ = get_grid_offset (_tmp6_);
		gtk_widget_set_margin_right ((GtkWidget*) _tmp5_, _tmp7_);
		_tmp8_ = self->priv->hbox;
		_tmp9_ = gtk_widget_get_allocated_height ((GtkWidget*) self);
		_tmp10_ = get_grid_offset (_tmp9_);
		gtk_widget_set_margin_top ((GtkWidget*) _tmp8_, _tmp10_);
		_tmp11_ = self->priv->hbox;
		_tmp12_ = gtk_widget_get_allocated_height ((GtkWidget*) self);
		_tmp13_ = get_grid_offset (_tmp12_);
		gtk_widget_set_margin_bottom ((GtkWidget*) _tmp11_, _tmp13_);
	}
}


static void main_window_shutdownbutton_clicked_cb (MainWindow* self, GtkButton* button) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	g_debug ("main-window.vala:218: shutdownbutton_clicked~~~~~~~~~~~~~~~~~~~~~~~~~~" \
"~~");
	main_window_show_shutdown_dialog (self, SHUTDOWN_DIALOG_TYPE_SHUTDOWN);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void main_window_keyboardbutton_clicked_cb (MainWindow* self, GtkToggleButton* button) {
	GtkToggleButton* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GtkWindow* _tmp3_ = NULL;
	GtkWindow* _tmp47_ = NULL;
	GtkToggleButton* _tmp48_ = NULL;
	gboolean _tmp49_ = FALSE;
	gboolean _tmp50_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	_tmp0_ = button;
	_tmp1_ = gtk_toggle_button_get_active (_tmp0_);
	_tmp2_ = _tmp1_;
	ug_settings_set_boolean (UG_SETTINGS_KEY_ONSCREEN_KEYBOARD, _tmp2_);
	_tmp3_ = self->priv->_keyboard_window;
	if (_tmp3_ == NULL) {
		gint id = 0;
		GtkSocket* keyboard_socket = NULL;
		GtkSocket* _tmp19_ = NULL;
		GtkSocket* _tmp20_ = NULL;
		GtkWindow* _tmp21_ = NULL;
		GtkWindow* _tmp22_ = NULL;
		GtkWindow* _tmp23_ = NULL;
		GtkWindow* _tmp24_ = NULL;
		GtkWindow* _tmp25_ = NULL;
		GtkSocket* _tmp26_ = NULL;
		GtkSocket* _tmp27_ = NULL;
		gint _tmp28_ = 0;
		GdkScreen* screen = NULL;
		GdkScreen* _tmp29_ = NULL;
		GdkScreen* _tmp30_ = NULL;
		gint monitor = 0;
		GdkScreen* _tmp31_ = NULL;
		GdkWindow* _tmp32_ = NULL;
		gint _tmp33_ = 0;
		GdkRectangle geom = {0};
		GdkScreen* _tmp34_ = NULL;
		gint _tmp35_ = 0;
		GdkRectangle _tmp36_ = {0};
		GtkWindow* _tmp37_ = NULL;
		GdkRectangle _tmp38_ = {0};
		gint _tmp39_ = 0;
		GdkRectangle _tmp40_ = {0};
		gint _tmp41_ = 0;
		GdkRectangle _tmp42_ = {0};
		gint _tmp43_ = 0;
		GtkWindow* _tmp44_ = NULL;
		GdkRectangle _tmp45_ = {0};
		gint _tmp46_ = 0;
		id = 0;
		{
			gchar** argv = NULL;
			gint argv_length1 = 0;
			gint _argv_size_ = 0;
			gint onboard_stdout_fd = 0;
			gchar** _tmp4_ = NULL;
			gint _tmp5_ = 0;
			gchar** _tmp6_ = NULL;
			gint _tmp6__length1 = 0;
			GPid _tmp7_ = 0;
			gint _tmp8_ = 0;
			FILE* f = NULL;
			gint _tmp9_ = 0;
			FILE* _tmp10_ = NULL;
			gchar* stdout_text = NULL;
			gchar* _tmp11_ = NULL;
			gint stdout_text_length1 = 0;
			gint _stdout_text_size_ = 0;
			FILE* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			gint _tmp13__length1 = 0;
			const gchar* _tmp14_ = NULL;
			g_shell_parse_argv ("onboard --xid", &_tmp5_, &_tmp4_, &_inner_error_);
			argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
			argv = _tmp4_;
			argv_length1 = _tmp5_;
			_argv_size_ = argv_length1;
			if (_inner_error_ != NULL) {
				argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
				goto __catch11_g_error;
			}
			_tmp6_ = argv;
			_tmp6__length1 = argv_length1;
			g_spawn_async_with_pipes (NULL, _tmp6_, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL, &_tmp7_, NULL, &_tmp8_, NULL, &_inner_error_);
			self->priv->keyboard_pid = _tmp7_;
			onboard_stdout_fd = _tmp8_;
			if (_inner_error_ != NULL) {
				argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
				goto __catch11_g_error;
			}
			_tmp9_ = onboard_stdout_fd;
			_tmp10_ = fdopen (_tmp9_, "r");
			f = _tmp10_;
			_tmp11_ = g_new0 (gchar, 1024);
			stdout_text = _tmp11_;
			stdout_text_length1 = 1024;
			_stdout_text_size_ = stdout_text_length1;
			_tmp12_ = f;
			_tmp13_ = stdout_text;
			_tmp13__length1 = stdout_text_length1;
			_tmp14_ = fgets (_tmp13_, _tmp13__length1, _tmp12_);
			if (_tmp14_ != NULL) {
				gchar* _tmp15_ = NULL;
				gint _tmp15__length1 = 0;
				gint _tmp16_ = 0;
				_tmp15_ = stdout_text;
				_tmp15__length1 = stdout_text_length1;
				_tmp16_ = atoi ((const gchar*) _tmp15_);
				id = _tmp16_;
			}
			stdout_text = (g_free (stdout_text), NULL);
			_fclose0 (f);
			argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
		}
		goto __finally11;
		__catch11_g_error:
		{
			GError* e = NULL;
			GError* _tmp17_ = NULL;
			const gchar* _tmp18_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp17_ = e;
			_tmp18_ = _tmp17_->message;
			g_warning ("main-window.vala:254: Error setting up keyboard: %s", _tmp18_);
			_g_error_free0 (e);
			return;
		}
		__finally11:
		if (_inner_error_ != NULL) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_tmp19_ = (GtkSocket*) gtk_socket_new ();
		g_object_ref_sink (_tmp19_);
		keyboard_socket = _tmp19_;
		_tmp20_ = keyboard_socket;
		gtk_widget_show ((GtkWidget*) _tmp20_);
		_tmp21_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
		g_object_ref_sink (_tmp21_);
		_tmp22_ = _tmp21_;
		main_window_set_keyboard_window (self, _tmp22_);
		_g_object_unref0 (_tmp22_);
		_tmp23_ = self->priv->_keyboard_window;
		gtk_window_set_accept_focus (_tmp23_, FALSE);
		_tmp24_ = self->priv->_keyboard_window;
		gtk_window_set_focus_on_map (_tmp24_, FALSE);
		_tmp25_ = self->priv->_keyboard_window;
		_tmp26_ = keyboard_socket;
		gtk_container_add ((GtkContainer*) _tmp25_, (GtkWidget*) _tmp26_);
		_tmp27_ = keyboard_socket;
		_tmp28_ = id;
		gtk_socket_add_id (_tmp27_, (Window) _tmp28_);
		_tmp29_ = gtk_window_get_screen ((GtkWindow*) self);
		_tmp30_ = _g_object_ref0 (_tmp29_);
		screen = _tmp30_;
		_tmp31_ = screen;
		_tmp32_ = gtk_widget_get_window ((GtkWidget*) self);
		_tmp33_ = gdk_screen_get_monitor_at_window (_tmp31_, _tmp32_);
		monitor = _tmp33_;
		_tmp34_ = screen;
		_tmp35_ = monitor;
		gdk_screen_get_monitor_geometry (_tmp34_, _tmp35_, &_tmp36_);
		geom = _tmp36_;
		_tmp37_ = self->priv->_keyboard_window;
		_tmp38_ = geom;
		_tmp39_ = _tmp38_.x;
		_tmp40_ = geom;
		_tmp41_ = _tmp40_.y;
		_tmp42_ = geom;
		_tmp43_ = _tmp42_.height;
		gtk_window_move (_tmp37_, _tmp39_, (_tmp41_ + _tmp43_) - 200);
		_tmp44_ = self->priv->_keyboard_window;
		_tmp45_ = geom;
		_tmp46_ = _tmp45_.width;
		gtk_window_resize (_tmp44_, _tmp46_, 200);
		_g_object_unref0 (screen);
		_g_object_unref0 (keyboard_socket);
	}
	_tmp47_ = self->priv->_keyboard_window;
	_tmp48_ = button;
	_tmp49_ = gtk_toggle_button_get_active (_tmp48_);
	_tmp50_ = _tmp49_;
	gtk_widget_set_visible ((GtkWidget*) _tmp47_, _tmp50_);
}


static gpointer _monitor_ref0 (gpointer self) {
	return self ? monitor_ref (self) : NULL;
}


static void main_window_monitors_changed_cb (MainWindow* self, GdkScreen* screen) {
	gint primary = 0;
	GdkScreen* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GdkScreen* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GdkScreen* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	Background* _tmp45_ = NULL;
	GList* _tmp46_ = NULL;
	GdkScreen* _tmp47_ = NULL;
	gint _tmp48_ = 0;
	GdkScreen* _tmp49_ = NULL;
	gint _tmp50_ = 0;
	Monitor* _tmp51_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (screen != NULL);
	_tmp0_ = screen;
	_tmp1_ = gdk_screen_get_primary_monitor (_tmp0_);
	primary = _tmp1_;
	_tmp2_ = screen;
	_tmp3_ = gdk_screen_get_width (_tmp2_);
	_tmp4_ = screen;
	_tmp5_ = gdk_screen_get_height (_tmp4_);
	g_debug ("main-window.vala:281: Screen is %dx%d pixels", _tmp3_, _tmp5_);
	__g_list_free__monitor_unref0_0 (self->priv->monitors);
	self->priv->monitors = NULL;
	_monitor_unref0 (self->priv->primary_monitor);
	self->priv->primary_monitor = NULL;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp6_ = FALSE;
			_tmp6_ = TRUE;
			while (TRUE) {
				gboolean _tmp7_ = FALSE;
				gint _tmp9_ = 0;
				GdkScreen* _tmp10_ = NULL;
				gint _tmp11_ = 0;
				GdkRectangle geometry = {0};
				GdkScreen* _tmp12_ = NULL;
				gint _tmp13_ = 0;
				GdkRectangle _tmp14_ = {0};
				gint _tmp15_ = 0;
				GdkRectangle _tmp16_ = {0};
				gint _tmp17_ = 0;
				GdkRectangle _tmp18_ = {0};
				gint _tmp19_ = 0;
				GdkRectangle _tmp20_ = {0};
				gint _tmp21_ = 0;
				GdkRectangle _tmp22_ = {0};
				gint _tmp23_ = 0;
				GdkScreen* _tmp24_ = NULL;
				gint _tmp25_ = 0;
				gboolean _tmp26_ = FALSE;
				_tmp7_ = _tmp6_;
				if (!_tmp7_) {
					gint _tmp8_ = 0;
					_tmp8_ = i;
					i = _tmp8_ + 1;
				}
				_tmp6_ = FALSE;
				_tmp9_ = i;
				_tmp10_ = screen;
				_tmp11_ = gdk_screen_get_n_monitors (_tmp10_);
				if (!(_tmp9_ < _tmp11_)) {
					break;
				}
				_tmp12_ = screen;
				_tmp13_ = i;
				gdk_screen_get_monitor_geometry (_tmp12_, _tmp13_, &_tmp14_);
				geometry = _tmp14_;
				_tmp15_ = i;
				_tmp16_ = geometry;
				_tmp17_ = _tmp16_.width;
				_tmp18_ = geometry;
				_tmp19_ = _tmp18_.height;
				_tmp20_ = geometry;
				_tmp21_ = _tmp20_.x;
				_tmp22_ = geometry;
				_tmp23_ = _tmp22_.y;
				g_debug ("main-window.vala:289: Monitor %d is %dx%d pixels at %d,%d", _tmp15_, _tmp17_, _tmp19_, _tmp21_, _tmp23_);
				_tmp24_ = screen;
				_tmp25_ = i;
				_tmp26_ = main_window_monitor_is_unique_position (self, _tmp24_, _tmp25_);
				if (_tmp26_) {
					Monitor* monitor = NULL;
					GdkRectangle _tmp27_ = {0};
					gint _tmp28_ = 0;
					GdkRectangle _tmp29_ = {0};
					gint _tmp30_ = 0;
					GdkRectangle _tmp31_ = {0};
					gint _tmp32_ = 0;
					GdkRectangle _tmp33_ = {0};
					gint _tmp34_ = 0;
					Monitor* _tmp35_ = NULL;
					Monitor* _tmp36_ = NULL;
					Monitor* _tmp37_ = NULL;
					gboolean _tmp38_ = FALSE;
					Monitor* _tmp39_ = NULL;
					gboolean _tmp42_ = FALSE;
					_tmp27_ = geometry;
					_tmp28_ = _tmp27_.x;
					_tmp29_ = geometry;
					_tmp30_ = _tmp29_.y;
					_tmp31_ = geometry;
					_tmp32_ = _tmp31_.width;
					_tmp33_ = geometry;
					_tmp34_ = _tmp33_.height;
					_tmp35_ = monitor_new (_tmp28_, _tmp30_, _tmp32_, _tmp34_);
					monitor = _tmp35_;
					_tmp36_ = monitor;
					_tmp37_ = _monitor_ref0 (_tmp36_);
					self->priv->monitors = g_list_append (self->priv->monitors, _tmp37_);
					_tmp39_ = self->priv->primary_monitor;
					if (_tmp39_ == NULL) {
						_tmp38_ = TRUE;
					} else {
						gint _tmp40_ = 0;
						gint _tmp41_ = 0;
						_tmp40_ = i;
						_tmp41_ = primary;
						_tmp38_ = _tmp40_ == _tmp41_;
					}
					_tmp42_ = _tmp38_;
					if (_tmp42_) {
						Monitor* _tmp43_ = NULL;
						Monitor* _tmp44_ = NULL;
						_tmp43_ = monitor;
						_tmp44_ = _monitor_ref0 (_tmp43_);
						_monitor_unref0 (self->priv->primary_monitor);
						self->priv->primary_monitor = _tmp44_;
					}
					_monitor_unref0 (monitor);
				}
			}
		}
	}
	_tmp45_ = self->priv->background;
	_tmp46_ = self->priv->monitors;
	background_set_monitors (_tmp45_, _tmp46_);
	_tmp47_ = screen;
	_tmp48_ = gdk_screen_get_width (_tmp47_);
	_tmp49_ = screen;
	_tmp50_ = gdk_screen_get_height (_tmp49_);
	gtk_window_resize ((GtkWindow*) self, _tmp48_, _tmp50_);
	gtk_window_move ((GtkWindow*) self, 0, 0);
	_tmp51_ = self->priv->primary_monitor;
	main_window_move_to_monitor (self, _tmp51_);
}


static gboolean main_window_monitor_is_unique_position (MainWindow* self, GdkScreen* screen, gint n) {
	gboolean result = FALSE;
	GdkRectangle g0 = {0};
	GdkScreen* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GdkRectangle _tmp2_ = {0};
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (screen != NULL, FALSE);
	_tmp0_ = screen;
	_tmp1_ = n;
	gdk_screen_get_monitor_geometry (_tmp0_, _tmp1_, &_tmp2_);
	g0 = _tmp2_;
	{
		gint i = 0;
		gint _tmp3_ = 0;
		_tmp3_ = n;
		i = _tmp3_ + 1;
		{
			gboolean _tmp4_ = FALSE;
			_tmp4_ = TRUE;
			while (TRUE) {
				gboolean _tmp5_ = FALSE;
				gint _tmp7_ = 0;
				GdkScreen* _tmp8_ = NULL;
				gint _tmp9_ = 0;
				GdkRectangle g1 = {0};
				GdkScreen* _tmp10_ = NULL;
				gint _tmp11_ = 0;
				GdkRectangle _tmp12_ = {0};
				gboolean _tmp13_ = FALSE;
				GdkRectangle _tmp14_ = {0};
				gint _tmp15_ = 0;
				GdkRectangle _tmp16_ = {0};
				gint _tmp17_ = 0;
				gboolean _tmp22_ = FALSE;
				_tmp5_ = _tmp4_;
				if (!_tmp5_) {
					gint _tmp6_ = 0;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp7_ = i;
				_tmp8_ = screen;
				_tmp9_ = gdk_screen_get_n_monitors (_tmp8_);
				if (!(_tmp7_ < _tmp9_)) {
					break;
				}
				_tmp10_ = screen;
				_tmp11_ = i;
				gdk_screen_get_monitor_geometry (_tmp10_, _tmp11_, &_tmp12_);
				g1 = _tmp12_;
				_tmp14_ = g0;
				_tmp15_ = _tmp14_.x;
				_tmp16_ = g1;
				_tmp17_ = _tmp16_.x;
				if (_tmp15_ == _tmp17_) {
					GdkRectangle _tmp18_ = {0};
					gint _tmp19_ = 0;
					GdkRectangle _tmp20_ = {0};
					gint _tmp21_ = 0;
					_tmp18_ = g0;
					_tmp19_ = _tmp18_.y;
					_tmp20_ = g1;
					_tmp21_ = _tmp20_.y;
					_tmp13_ = _tmp19_ == _tmp21_;
				} else {
					_tmp13_ = FALSE;
				}
				_tmp22_ = _tmp13_;
				if (_tmp22_) {
					result = FALSE;
					return result;
				}
			}
		}
	}
	result = TRUE;
	return result;
}


static gboolean main_window_real_motion_notify_event (GtkWidget* base, GdkEventMotion* event) {
	MainWindow * self;
	gboolean result = FALSE;
	gint x = 0;
	GdkEventMotion _tmp0_ = {0};
	gdouble _tmp1_ = 0.0;
	gint y = 0;
	GdkEventMotion _tmp2_ = {0};
	gdouble _tmp3_ = 0.0;
	GdkEventMotion _tmp4_ = {0};
	GdkWindow* _tmp5_ = NULL;
	GdkWindow* _tmp6_ = NULL;
	GList* _tmp22_ = NULL;
	self = (MainWindow*) base;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = *event;
	_tmp1_ = _tmp0_.x;
	x = (gint) (_tmp1_ + 0.5);
	_tmp2_ = *event;
	_tmp3_ = _tmp2_.y;
	y = (gint) (_tmp3_ + 0.5);
	_tmp4_ = *event;
	_tmp5_ = _tmp4_.window;
	_tmp6_ = gtk_widget_get_window ((GtkWidget*) self);
	if (_tmp5_ != _tmp6_) {
		gint w_x = 0;
		gint w_y = 0;
		GdkWindow* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
		GdkEventMotion _tmp14_ = {0};
		GdkWindow* _tmp15_ = NULL;
		gint _tmp16_ = 0;
		gint _tmp17_ = 0;
		gint _tmp18_ = 0;
		gint _tmp19_ = 0;
		gint _tmp20_ = 0;
		gint _tmp21_ = 0;
		_tmp7_ = gtk_widget_get_window ((GtkWidget*) self);
		gdk_window_get_origin (_tmp7_, &_tmp8_, &_tmp9_);
		w_x = _tmp8_;
		w_y = _tmp9_;
		_tmp10_ = x;
		_tmp11_ = w_x;
		x = _tmp10_ - _tmp11_;
		_tmp12_ = y;
		_tmp13_ = w_y;
		y = _tmp12_ - _tmp13_;
		_tmp14_ = *event;
		_tmp15_ = _tmp14_.window;
		gdk_window_get_origin (_tmp15_, &_tmp16_, &_tmp17_);
		w_x = _tmp16_;
		w_y = _tmp17_;
		_tmp18_ = x;
		_tmp19_ = w_x;
		x = _tmp18_ + _tmp19_;
		_tmp20_ = y;
		_tmp21_ = w_y;
		y = _tmp20_ + _tmp21_;
	}
	_tmp22_ = self->priv->monitors;
	{
		GList* m_collection = NULL;
		GList* m_it = NULL;
		m_collection = _tmp22_;
		for (m_it = m_collection; m_it != NULL; m_it = m_it->next) {
			Monitor* _tmp23_ = NULL;
			Monitor* m = NULL;
			_tmp23_ = _monitor_ref0 ((Monitor*) m_it->data);
			m = _tmp23_;
			{
				gboolean _tmp24_ = FALSE;
				gboolean _tmp25_ = FALSE;
				gboolean _tmp26_ = FALSE;
				gint _tmp27_ = 0;
				Monitor* _tmp28_ = NULL;
				gint _tmp29_ = 0;
				gboolean _tmp35_ = FALSE;
				gboolean _tmp39_ = FALSE;
				gboolean _tmp45_ = FALSE;
				_tmp27_ = x;
				_tmp28_ = m;
				_tmp29_ = _tmp28_->x;
				if (_tmp27_ >= _tmp29_) {
					gint _tmp30_ = 0;
					Monitor* _tmp31_ = NULL;
					gint _tmp32_ = 0;
					Monitor* _tmp33_ = NULL;
					gint _tmp34_ = 0;
					_tmp30_ = x;
					_tmp31_ = m;
					_tmp32_ = _tmp31_->x;
					_tmp33_ = m;
					_tmp34_ = _tmp33_->width;
					_tmp26_ = _tmp30_ <= (_tmp32_ + _tmp34_);
				} else {
					_tmp26_ = FALSE;
				}
				_tmp35_ = _tmp26_;
				if (_tmp35_) {
					gint _tmp36_ = 0;
					Monitor* _tmp37_ = NULL;
					gint _tmp38_ = 0;
					_tmp36_ = y;
					_tmp37_ = m;
					_tmp38_ = _tmp37_->y;
					_tmp25_ = _tmp36_ >= _tmp38_;
				} else {
					_tmp25_ = FALSE;
				}
				_tmp39_ = _tmp25_;
				if (_tmp39_) {
					gint _tmp40_ = 0;
					Monitor* _tmp41_ = NULL;
					gint _tmp42_ = 0;
					Monitor* _tmp43_ = NULL;
					gint _tmp44_ = 0;
					_tmp40_ = y;
					_tmp41_ = m;
					_tmp42_ = _tmp41_->y;
					_tmp43_ = m;
					_tmp44_ = _tmp43_->height;
					_tmp24_ = _tmp40_ <= (_tmp42_ + _tmp44_);
				} else {
					_tmp24_ = FALSE;
				}
				_tmp45_ = _tmp24_;
				if (_tmp45_) {
					Monitor* _tmp46_ = NULL;
					_tmp46_ = m;
					main_window_move_to_monitor (self, _tmp46_);
					_monitor_unref0 (m);
					break;
				}
				_monitor_unref0 (m);
			}
		}
	}
	result = FALSE;
	return result;
}


static void main_window_move_to_monitor (MainWindow* self, Monitor* monitor) {
	Monitor* _tmp0_ = NULL;
	Monitor* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	Monitor* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	Monitor* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	Background* _tmp7_ = NULL;
	Monitor* _tmp8_ = NULL;
	Background* _tmp9_ = NULL;
	GtkBox* _tmp10_ = NULL;
	Monitor* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	Monitor* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	ShutdownDialog* _tmp15_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (monitor != NULL);
	_tmp0_ = monitor;
	_tmp1_ = _monitor_ref0 (_tmp0_);
	_monitor_unref0 (self->priv->active_monitor);
	self->priv->active_monitor = _tmp1_;
	_tmp2_ = self->priv->login_box;
	_tmp3_ = monitor;
	_tmp4_ = _tmp3_->width;
	_tmp5_ = monitor;
	_tmp6_ = _tmp5_->height;
	gtk_widget_set_size_request ((GtkWidget*) _tmp2_, _tmp4_, _tmp6_);
	_tmp7_ = self->priv->background;
	_tmp8_ = monitor;
	background_set_active_monitor (_tmp7_, _tmp8_);
	_tmp9_ = self->priv->background;
	_tmp10_ = self->priv->login_box;
	_tmp11_ = monitor;
	_tmp12_ = _tmp11_->x;
	_tmp13_ = monitor;
	_tmp14_ = _tmp13_->y;
	gtk_fixed_move ((GtkFixed*) _tmp9_, (GtkWidget*) _tmp10_, _tmp12_, _tmp14_);
	_tmp15_ = self->priv->shutdown_dialog;
	if (_tmp15_ != NULL) {
		ShutdownDialog* _tmp16_ = NULL;
		Monitor* _tmp17_ = NULL;
		Background* _tmp18_ = NULL;
		ShutdownDialog* _tmp19_ = NULL;
		Monitor* _tmp20_ = NULL;
		gint _tmp21_ = 0;
		Monitor* _tmp22_ = NULL;
		gint _tmp23_ = 0;
		_tmp16_ = self->priv->shutdown_dialog;
		_tmp17_ = monitor;
		shutdown_dialog_set_active_monitor (_tmp16_, _tmp17_);
		_tmp18_ = self->priv->background;
		_tmp19_ = self->priv->shutdown_dialog;
		_tmp20_ = monitor;
		_tmp21_ = _tmp20_->x;
		_tmp22_ = monitor;
		_tmp23_ = _tmp22_->y;
		gtk_fixed_move ((GtkFixed*) _tmp18_, (GtkWidget*) _tmp19_, _tmp21_, _tmp23_);
	}
}


static void main_window_add_user_list (MainWindow* self) {
	GreeterList* greeter_list = NULL;
	Background* _tmp0_ = NULL;
	UserList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->background;
	_tmp1_ = user_list_new (_tmp0_);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (greeter_list);
	greeter_list = (GreeterList*) _tmp1_;
	gtk_widget_show ((GtkWidget*) greeter_list);
	unity_greeter_add_style_class ((GtkWidget*) greeter_list);
	main_window_push_list (self, greeter_list);
	_g_object_unref0 (greeter_list);
}


static gboolean main_window_real_key_press_event (GtkWidget* base, GdkEventKey* event) {
	MainWindow * self;
	gboolean result = FALSE;
	GreeterList* top = NULL;
	ListStack* _tmp0_ = NULL;
	GreeterList* _tmp1_ = NULL;
	ListStack* _tmp2_ = NULL;
	GreeterList* _tmp3_ = NULL;
	GreeterList* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	GdkEventKey _tmp53_ = {0};
	guint _tmp54_ = 0U;
	GdkEventKey _tmp96_ = {0};
	gboolean _tmp97_ = FALSE;
	self = (MainWindow*) base;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->stack;
	_tmp1_ = list_stack_top (_tmp0_);
	top = _tmp1_;
	_tmp2_ = self->stack;
	_tmp3_ = list_stack_top (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, TYPE_USER_LIST);
	_g_object_unref0 (_tmp4_);
	if (_tmp5_) {
		UserList* user_list = NULL;
		ListStack* _tmp6_ = NULL;
		GreeterList* _tmp7_ = NULL;
		UserList* _tmp8_ = NULL;
		UserList* _tmp9_ = NULL;
		gboolean _tmp10_ = FALSE;
		gboolean _tmp11_ = FALSE;
		_tmp6_ = self->stack;
		_tmp7_ = list_stack_top (_tmp6_);
		_tmp8_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, TYPE_USER_LIST) ? ((UserList*) _tmp7_) : NULL;
		if (_tmp8_ == NULL) {
			_g_object_unref0 (_tmp7_);
		}
		user_list = _tmp8_;
		_tmp9_ = user_list;
		_tmp10_ = user_list_get_show_hidden_users (_tmp9_);
		_tmp11_ = _tmp10_;
		if (!_tmp11_) {
			GdkModifierType shift_mask = 0;
			GdkModifierType control_mask = 0;
			GdkModifierType alt_mask = 0;
			gboolean _tmp12_ = FALSE;
			gboolean _tmp13_ = FALSE;
			gboolean _tmp14_ = FALSE;
			gboolean _tmp15_ = FALSE;
			GdkEventKey _tmp16_ = {0};
			guint _tmp17_ = 0U;
			gboolean _tmp20_ = FALSE;
			gboolean _tmp25_ = FALSE;
			gboolean _tmp38_ = FALSE;
			gboolean _tmp51_ = FALSE;
			shift_mask = GDK_CONTROL_MASK | GDK_MOD1_MASK;
			control_mask = GDK_SHIFT_MASK | GDK_MOD1_MASK;
			alt_mask = GDK_CONTROL_MASK | GDK_SHIFT_MASK;
			_tmp16_ = *event;
			_tmp17_ = _tmp16_.keyval;
			if (_tmp17_ == ((guint) GDK_KEY_Shift_L)) {
				_tmp15_ = TRUE;
			} else {
				GdkEventKey _tmp18_ = {0};
				guint _tmp19_ = 0U;
				_tmp18_ = *event;
				_tmp19_ = _tmp18_.keyval;
				_tmp15_ = _tmp19_ == ((guint) GDK_KEY_Shift_R);
			}
			_tmp20_ = _tmp15_;
			if (_tmp20_) {
				GdkEventKey _tmp21_ = {0};
				GdkModifierType _tmp22_ = 0;
				GdkModifierType _tmp23_ = 0;
				GdkModifierType _tmp24_ = 0;
				_tmp21_ = *event;
				_tmp22_ = _tmp21_.state;
				_tmp23_ = shift_mask;
				_tmp24_ = shift_mask;
				_tmp14_ = (_tmp22_ & _tmp23_) == _tmp24_;
			} else {
				_tmp14_ = FALSE;
			}
			_tmp25_ = _tmp14_;
			if (_tmp25_) {
				_tmp13_ = TRUE;
			} else {
				gboolean _tmp26_ = FALSE;
				gboolean _tmp27_ = FALSE;
				GdkEventKey _tmp28_ = {0};
				guint _tmp29_ = 0U;
				gboolean _tmp32_ = FALSE;
				gboolean _tmp37_ = FALSE;
				_tmp28_ = *event;
				_tmp29_ = _tmp28_.keyval;
				if (_tmp29_ == ((guint) GDK_KEY_Control_L)) {
					_tmp27_ = TRUE;
				} else {
					GdkEventKey _tmp30_ = {0};
					guint _tmp31_ = 0U;
					_tmp30_ = *event;
					_tmp31_ = _tmp30_.keyval;
					_tmp27_ = _tmp31_ == ((guint) GDK_KEY_Control_R);
				}
				_tmp32_ = _tmp27_;
				if (_tmp32_) {
					GdkEventKey _tmp33_ = {0};
					GdkModifierType _tmp34_ = 0;
					GdkModifierType _tmp35_ = 0;
					GdkModifierType _tmp36_ = 0;
					_tmp33_ = *event;
					_tmp34_ = _tmp33_.state;
					_tmp35_ = control_mask;
					_tmp36_ = control_mask;
					_tmp26_ = (_tmp34_ & _tmp35_) == _tmp36_;
				} else {
					_tmp26_ = FALSE;
				}
				_tmp37_ = _tmp26_;
				_tmp13_ = _tmp37_;
			}
			_tmp38_ = _tmp13_;
			if (_tmp38_) {
				_tmp12_ = TRUE;
			} else {
				gboolean _tmp39_ = FALSE;
				gboolean _tmp40_ = FALSE;
				GdkEventKey _tmp41_ = {0};
				guint _tmp42_ = 0U;
				gboolean _tmp45_ = FALSE;
				gboolean _tmp50_ = FALSE;
				_tmp41_ = *event;
				_tmp42_ = _tmp41_.keyval;
				if (_tmp42_ == ((guint) GDK_KEY_Alt_L)) {
					_tmp40_ = TRUE;
				} else {
					GdkEventKey _tmp43_ = {0};
					guint _tmp44_ = 0U;
					_tmp43_ = *event;
					_tmp44_ = _tmp43_.keyval;
					_tmp40_ = _tmp44_ == ((guint) GDK_KEY_Alt_R);
				}
				_tmp45_ = _tmp40_;
				if (_tmp45_) {
					GdkEventKey _tmp46_ = {0};
					GdkModifierType _tmp47_ = 0;
					GdkModifierType _tmp48_ = 0;
					GdkModifierType _tmp49_ = 0;
					_tmp46_ = *event;
					_tmp47_ = _tmp46_.state;
					_tmp48_ = alt_mask;
					_tmp49_ = alt_mask;
					_tmp39_ = (_tmp47_ & _tmp48_) == _tmp49_;
				} else {
					_tmp39_ = FALSE;
				}
				_tmp50_ = _tmp39_;
				_tmp12_ = _tmp50_;
			}
			_tmp51_ = _tmp12_;
			if (_tmp51_) {
				UserList* _tmp52_ = NULL;
				g_debug ("main-window.vala:393: Hidden user key combination detected");
				_tmp52_ = user_list;
				user_list_set_show_hidden_users (_tmp52_, TRUE);
				result = TRUE;
				_g_object_unref0 (user_list);
				_g_object_unref0 (top);
				return result;
			}
		}
		_g_object_unref0 (user_list);
	}
	_tmp53_ = *event;
	_tmp54_ = _tmp53_.keyval;
	switch (_tmp54_) {
		case GDK_KEY_Escape:
		{
			GtkBox* _tmp55_ = NULL;
			gboolean _tmp56_ = FALSE;
			gboolean _tmp57_ = FALSE;
			ShutdownDialog* _tmp59_ = NULL;
			_tmp55_ = self->priv->login_box;
			_tmp56_ = gtk_widget_get_sensitive ((GtkWidget*) _tmp55_);
			_tmp57_ = _tmp56_;
			if (_tmp57_) {
				GreeterList* _tmp58_ = NULL;
				_tmp58_ = top;
				greeter_list_cancel_authentication (_tmp58_);
			}
			_tmp59_ = self->priv->shutdown_dialog;
			if (_tmp59_ != NULL) {
				ShutdownDialog* _tmp60_ = NULL;
				_tmp60_ = self->priv->shutdown_dialog;
				shutdown_dialog_cancel (_tmp60_);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_Page_Up:
		case GDK_KEY_KP_Page_Up:
		{
			GtkBox* _tmp61_ = NULL;
			gboolean _tmp62_ = FALSE;
			gboolean _tmp63_ = FALSE;
			_tmp61_ = self->priv->login_box;
			_tmp62_ = gtk_widget_get_sensitive ((GtkWidget*) _tmp61_);
			_tmp63_ = _tmp62_;
			if (_tmp63_) {
				GreeterList* _tmp64_ = NULL;
				_tmp64_ = top;
				greeter_list_scroll (_tmp64_, GREETER_LIST_SCROLL_TARGET_START);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_Page_Down:
		case GDK_KEY_KP_Page_Down:
		{
			GtkBox* _tmp65_ = NULL;
			gboolean _tmp66_ = FALSE;
			gboolean _tmp67_ = FALSE;
			_tmp65_ = self->priv->login_box;
			_tmp66_ = gtk_widget_get_sensitive ((GtkWidget*) _tmp65_);
			_tmp67_ = _tmp66_;
			if (_tmp67_) {
				GreeterList* _tmp68_ = NULL;
				_tmp68_ = top;
				greeter_list_scroll (_tmp68_, GREETER_LIST_SCROLL_TARGET_END);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_Up:
		case GDK_KEY_KP_Up:
		{
			GtkBox* _tmp69_ = NULL;
			gboolean _tmp70_ = FALSE;
			gboolean _tmp71_ = FALSE;
			_tmp69_ = self->priv->login_box;
			_tmp70_ = gtk_widget_get_sensitive ((GtkWidget*) _tmp69_);
			_tmp71_ = _tmp70_;
			if (_tmp71_) {
				GreeterList* _tmp72_ = NULL;
				_tmp72_ = top;
				greeter_list_scroll (_tmp72_, GREETER_LIST_SCROLL_TARGET_UP);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_Down:
		case GDK_KEY_KP_Down:
		{
			GtkBox* _tmp73_ = NULL;
			gboolean _tmp74_ = FALSE;
			gboolean _tmp75_ = FALSE;
			_tmp73_ = self->priv->login_box;
			_tmp74_ = gtk_widget_get_sensitive ((GtkWidget*) _tmp73_);
			_tmp75_ = _tmp74_;
			if (_tmp75_) {
				GreeterList* _tmp76_ = NULL;
				_tmp76_ = top;
				greeter_list_scroll (_tmp76_, GREETER_LIST_SCROLL_TARGET_DOWN);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_Left:
		case GDK_KEY_KP_Left:
		{
			ShutdownDialog* _tmp77_ = NULL;
			_tmp77_ = self->priv->shutdown_dialog;
			if (_tmp77_ != NULL) {
				ShutdownDialog* _tmp78_ = NULL;
				_tmp78_ = self->priv->shutdown_dialog;
				shutdown_dialog_focus_prev (_tmp78_);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_Right:
		case GDK_KEY_KP_Right:
		{
			ShutdownDialog* _tmp79_ = NULL;
			_tmp79_ = self->priv->shutdown_dialog;
			if (_tmp79_ != NULL) {
				ShutdownDialog* _tmp80_ = NULL;
				_tmp80_ = self->priv->shutdown_dialog;
				shutdown_dialog_focus_next (_tmp80_);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_F10:
		{
			GtkBox* _tmp81_ = NULL;
			gboolean _tmp82_ = FALSE;
			gboolean _tmp83_ = FALSE;
			_tmp81_ = self->priv->login_box;
			_tmp82_ = gtk_widget_get_sensitive ((GtkWidget*) _tmp81_);
			_tmp83_ = _tmp82_;
			if (_tmp83_) {
				main_window_show_shutdown_dialog (self, SHUTDOWN_DIALOG_TYPE_SHUTDOWN);
			}
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_PowerOff:
		{
			main_window_show_shutdown_dialog (self, SHUTDOWN_DIALOG_TYPE_SHUTDOWN);
			result = TRUE;
			_g_object_unref0 (top);
			return result;
		}
		case GDK_KEY_z:
		{
			gboolean _tmp84_ = FALSE;
			UnityGreeter* _tmp85_ = NULL;
			gboolean _tmp86_ = FALSE;
			gboolean _tmp89_ = FALSE;
			_tmp85_ = unity_greeter_singleton;
			_tmp86_ = _tmp85_->test_mode;
			if (_tmp86_) {
				GdkEventKey _tmp87_ = {0};
				GdkModifierType _tmp88_ = 0;
				_tmp87_ = *event;
				_tmp88_ = _tmp87_.state;
				_tmp84_ = (_tmp88_ & GDK_MOD1_MASK) != 0;
			} else {
				_tmp84_ = FALSE;
			}
			_tmp89_ = _tmp84_;
			if (_tmp89_) {
				main_window_show_shutdown_dialog (self, SHUTDOWN_DIALOG_TYPE_SHUTDOWN);
				result = TRUE;
				_g_object_unref0 (top);
				return result;
			}
			break;
		}
		case GDK_KEY_Z:
		{
			gboolean _tmp90_ = FALSE;
			UnityGreeter* _tmp91_ = NULL;
			gboolean _tmp92_ = FALSE;
			gboolean _tmp95_ = FALSE;
			_tmp91_ = unity_greeter_singleton;
			_tmp92_ = _tmp91_->test_mode;
			if (_tmp92_) {
				GdkEventKey _tmp93_ = {0};
				GdkModifierType _tmp94_ = 0;
				_tmp93_ = *event;
				_tmp94_ = _tmp93_.state;
				_tmp90_ = (_tmp94_ & GDK_MOD1_MASK) != 0;
			} else {
				_tmp90_ = FALSE;
			}
			_tmp95_ = _tmp90_;
			if (_tmp95_) {
				main_window_show_shutdown_dialog (self, SHUTDOWN_DIALOG_TYPE_RESTART);
				result = TRUE;
				_g_object_unref0 (top);
				return result;
			}
			break;
		}
		default:
		break;
	}
	_tmp96_ = *event;
	_tmp97_ = GTK_WIDGET_CLASS (main_window_parent_class)->key_press_event ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_WINDOW, GtkWindow), &_tmp96_);
	result = _tmp97_;
	_g_object_unref0 (top);
	return result;
}


void main_window_set_keyboard_state (MainWindow* self) {
	GtkToggleButton* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	g_debug ("main-window.vala:466: ~~~~~~~~~set_keyboard_state~~~~~~~~~~");
	_tmp0_ = self->priv->a11ybutton;
	_tmp1_ = ug_settings_get_boolean (UG_SETTINGS_KEY_ONSCREEN_KEYBOARD);
	gtk_toggle_button_set_active (_tmp0_, _tmp1_);
}


static void _main_window_close_shutdown_dialog_shutdown_dialog_closed (ShutdownDialog* _sender, gpointer self) {
	main_window_close_shutdown_dialog (self);
}


void main_window_show_shutdown_dialog (MainWindow* self, ShutdownDialogType type) {
	ShutdownDialog* _tmp0_ = NULL;
	GtkBox* _tmp2_ = NULL;
	ShutdownDialogType _tmp3_ = 0;
	Background* _tmp4_ = NULL;
	ShutdownDialog* _tmp5_ = NULL;
	ShutdownDialog* _tmp6_ = NULL;
	Background* _tmp7_ = NULL;
	ShutdownDialog* _tmp8_ = NULL;
	Monitor* _tmp9_ = NULL;
	ShutdownDialog* _tmp10_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->shutdown_dialog;
	if (_tmp0_ != NULL) {
		ShutdownDialog* _tmp1_ = NULL;
		_tmp1_ = self->priv->shutdown_dialog;
		gtk_widget_destroy ((GtkWidget*) _tmp1_);
	}
	_tmp2_ = self->priv->login_box;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp2_, FALSE);
	_tmp3_ = type;
	_tmp4_ = self->priv->background;
	_tmp5_ = shutdown_dialog_new (_tmp3_, _tmp4_);
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->shutdown_dialog);
	self->priv->shutdown_dialog = _tmp5_;
	_tmp6_ = self->priv->shutdown_dialog;
	g_signal_connect_object (_tmp6_, "closed", (GCallback) _main_window_close_shutdown_dialog_shutdown_dialog_closed, self, 0);
	_tmp7_ = self->priv->background;
	_tmp8_ = self->priv->shutdown_dialog;
	gtk_container_add ((GtkContainer*) _tmp7_, (GtkWidget*) _tmp8_);
	_tmp9_ = self->priv->active_monitor;
	main_window_move_to_monitor (self, _tmp9_);
	_tmp10_ = self->priv->shutdown_dialog;
	gtk_widget_set_visible ((GtkWidget*) _tmp10_, TRUE);
}


void main_window_close_shutdown_dialog (MainWindow* self) {
	ShutdownDialog* _tmp0_ = NULL;
	ShutdownDialog* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->shutdown_dialog;
	if (_tmp0_ == NULL) {
		return;
	}
	_tmp1_ = self->priv->shutdown_dialog;
	gtk_widget_destroy ((GtkWidget*) _tmp1_);
	_g_object_unref0 (self->priv->shutdown_dialog);
	self->priv->shutdown_dialog = NULL;
	_tmp2_ = self->priv->login_box;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp2_, TRUE);
}


MainWindow* main_window_construct (GType object_type) {
	MainWindow * self = NULL;
	self = (MainWindow*) g_object_new (object_type, NULL);
	return self;
}


MainWindow* main_window_new (void) {
	return main_window_construct (TYPE_MAIN_WINDOW);
}


GtkWindow* main_window_get_keyboard_window (MainWindow* self) {
	GtkWindow* result;
	GtkWindow* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_keyboard_window;
	result = _tmp0_;
	return result;
}


static void main_window_set_keyboard_window (MainWindow* self, GtkWindow* value) {
	GtkWindow* _tmp0_ = NULL;
	GtkWindow* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_keyboard_window);
	self->priv->_keyboard_window = _tmp1_;
	g_object_notify ((GObject *) self, "keyboard-window");
}


static void _main_window_keyboardbutton_clicked_cb_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	main_window_keyboardbutton_clicked_cb (self, _sender);
}


static void _main_window_shutdownbutton_clicked_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_shutdownbutton_clicked_cb (self, _sender);
}


static void _main_window_pop_list_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_pop_list (self);
}


static void _main_window_monitors_changed_cb_gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self) {
	main_window_monitors_changed_cb (self, _sender);
}


static GObject * main_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MainWindow * self;
	GdkEventMask _tmp0_ = 0;
	GdkEventMask _tmp1_ = 0;
	GtkAccelGroup* accel_group = NULL;
	GtkAccelGroup* _tmp2_ = NULL;
	GtkAccelGroup* _tmp3_ = NULL;
	GdkRGBA bg_color = {0};
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GdkRGBA _tmp6_ = {0};
	AtkObject* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GdkWindow* _tmp9_ = NULL;
	cairo_t* _tmp10_ = NULL;
	cairo_t* _tmp11_ = NULL;
	cairo_surface_t* _tmp12_ = NULL;
	Background* _tmp13_ = NULL;
	Background* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	Background* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	Background* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	Background* _tmp24_ = NULL;
	Background* _tmp25_ = NULL;
	Background* _tmp26_ = NULL;
	GtkBox* _tmp27_ = NULL;
	GtkBox* _tmp28_ = NULL;
	Background* _tmp29_ = NULL;
	GtkBox* _tmp30_ = NULL;
	GtkHButtonBox* buttonbox = NULL;
	GtkHButtonBox* _tmp31_ = NULL;
	GtkHButtonBox* _tmp32_ = NULL;
	GtkHButtonBox* _tmp33_ = NULL;
	gchar* shadow_style = NULL;
	gchar* _tmp34_ = NULL;
	GtkHButtonBox* _tmp47_ = NULL;
	GtkHButtonBox* _tmp48_ = NULL;
	GtkAlignment* buttonbox_align = NULL;
	GtkAlignment* _tmp49_ = NULL;
	GtkAlignment* _tmp50_ = NULL;
	GtkBox* _tmp51_ = NULL;
	GtkAlignment* _tmp52_ = NULL;
	GtkAlignment* _tmp53_ = NULL;
	GtkHButtonBox* _tmp54_ = NULL;
	GtkHButtonBox* _tmp55_ = NULL;
	GtkAlignment* a11yalign = NULL;
	GtkAlignment* _tmp56_ = NULL;
	GtkAlignment* _tmp57_ = NULL;
	GtkHButtonBox* _tmp58_ = NULL;
	GtkAlignment* _tmp59_ = NULL;
	GtkToggleButton* _tmp60_ = NULL;
	GtkToggleButton* _tmp61_ = NULL;
	GtkImage* a11ybuttonimage = NULL;
	gchar* _tmp62_ = NULL;
	gchar* _tmp63_ = NULL;
	GtkImage* _tmp64_ = NULL;
	GtkImage* _tmp65_ = NULL;
	GtkImage* _tmp66_ = NULL;
	GtkToggleButton* _tmp67_ = NULL;
	GtkImage* _tmp68_ = NULL;
	GtkToggleButton* _tmp69_ = NULL;
	GtkAlignment* _tmp70_ = NULL;
	GtkToggleButton* _tmp71_ = NULL;
	GtkToggleButton* _tmp72_ = NULL;
	GtkAlignment* shutdownbutton_align = NULL;
	GtkAlignment* _tmp73_ = NULL;
	GtkAlignment* _tmp74_ = NULL;
	GtkHButtonBox* _tmp75_ = NULL;
	GtkAlignment* _tmp76_ = NULL;
	GtkAlignment* _tmp77_ = NULL;
	GtkButton* _tmp78_ = NULL;
	GtkButton* _tmp79_ = NULL;
	GtkImage* shutdownbutton_image = NULL;
	gchar* _tmp80_ = NULL;
	gchar* _tmp81_ = NULL;
	GtkImage* _tmp82_ = NULL;
	GtkImage* _tmp83_ = NULL;
	GtkImage* _tmp84_ = NULL;
	GtkButton* _tmp85_ = NULL;
	GtkImage* _tmp86_ = NULL;
	GtkButton* _tmp87_ = NULL;
	GtkAlignment* _tmp88_ = NULL;
	GtkButton* _tmp89_ = NULL;
	GtkButton* _tmp90_ = NULL;
	GtkBox* _tmp91_ = NULL;
	GtkBox* _tmp92_ = NULL;
	GtkBox* _tmp93_ = NULL;
	GtkBox* _tmp94_ = NULL;
	GtkBox* _tmp95_ = NULL;
	GtkAlignment* align = NULL;
	GtkAlignment* _tmp96_ = NULL;
	GtkAlignment* _tmp97_ = NULL;
	GtkAlignment* _tmp98_ = NULL;
	GtkAlignment* _tmp99_ = NULL;
	GtkBox* _tmp100_ = NULL;
	GtkAlignment* _tmp101_ = NULL;
	FlatButton* _tmp102_ = NULL;
	GtkButton* _tmp103_ = NULL;
	AtkObject* _tmp104_ = NULL;
	const gchar* _tmp105_ = NULL;
	GtkButton* _tmp106_ = NULL;
	GtkImage* image = NULL;
	gchar* _tmp107_ = NULL;
	gchar* _tmp108_ = NULL;
	GtkImage* _tmp109_ = NULL;
	GtkImage* _tmp110_ = NULL;
	GtkImage* _tmp111_ = NULL;
	GtkButton* _tmp112_ = NULL;
	GtkButton* _tmp113_ = NULL;
	GtkImage* _tmp114_ = NULL;
	GtkButton* _tmp115_ = NULL;
	GtkAlignment* _tmp116_ = NULL;
	GtkButton* _tmp117_ = NULL;
	GtkAlignment* _tmp118_ = NULL;
	GtkAlignment* _tmp119_ = NULL;
	GtkBox* _tmp120_ = NULL;
	GtkAlignment* _tmp121_ = NULL;
	ListStack* _tmp122_ = NULL;
	ListStack* _tmp123_ = NULL;
	GtkAlignment* _tmp124_ = NULL;
	ListStack* _tmp125_ = NULL;
	UnityGreeter* _tmp126_ = NULL;
	gboolean _tmp127_ = FALSE;
	GError * _inner_error_ = NULL;
	parent_class = G_OBJECT_CLASS (main_window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN_WINDOW, MainWindow);
	_tmp0_ = gtk_widget_get_events ((GtkWidget*) self);
	_tmp1_ = _tmp0_;
	gtk_widget_set_events ((GtkWidget*) self, _tmp1_ | GDK_POINTER_MOTION_MASK);
	_tmp2_ = gtk_accel_group_new ();
	accel_group = _tmp2_;
	_tmp3_ = accel_group;
	gtk_window_add_accel_group ((GtkWindow*) self, _tmp3_);
	memset (&bg_color, 0, sizeof (GdkRGBA));
	_tmp4_ = ug_settings_get_string (UG_SETTINGS_KEY_BACKGROUND_COLOR);
	_tmp5_ = _tmp4_;
	gdk_rgba_parse (&bg_color, _tmp5_);
	_g_free0 (_tmp5_);
	_tmp6_ = bg_color;
	gtk_widget_override_background_color ((GtkWidget*) self, GTK_STATE_FLAG_NORMAL, &_tmp6_);
	_tmp7_ = gtk_widget_get_accessible ((GtkWidget*) self);
	_tmp8_ = _ ("Login Screen");
	atk_object_set_name (_tmp7_, _tmp8_);
	gtk_window_set_has_resize_grip ((GtkWindow*) self, FALSE);
	unity_greeter_add_style_class ((GtkWidget*) self);
	gtk_widget_realize ((GtkWidget*) self);
	_tmp9_ = gtk_widget_get_window ((GtkWidget*) self);
	_tmp10_ = gdk_cairo_create (_tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = cairo_get_target (_tmp11_);
	_tmp13_ = background_new (_tmp12_);
	g_object_ref_sink (_tmp13_);
	_g_object_unref0 (self->priv->background);
	self->priv->background = _tmp13_;
	_cairo_destroy0 (_tmp11_);
	_tmp14_ = self->priv->background;
	_tmp15_ = ug_settings_get_boolean (UG_SETTINGS_KEY_DRAW_GRID);
	background_set_draw_grid (_tmp14_, _tmp15_);
	_tmp16_ = self->priv->background;
	_tmp17_ = ug_settings_get_string (UG_SETTINGS_KEY_BACKGROUND);
	_tmp18_ = _tmp17_;
	background_set_default_background (_tmp16_, _tmp18_);
	_g_free0 (_tmp18_);
	_tmp19_ = self->priv->background;
	_tmp20_ = ug_settings_get_string (UG_SETTINGS_KEY_LOGO);
	_tmp21_ = _tmp20_;
	_tmp22_ = ug_settings_get_string (UG_SETTINGS_KEY_BACKGROUND_LOGO);
	_tmp23_ = _tmp22_;
	background_set_logo (_tmp19_, _tmp21_, _tmp23_);
	_g_free0 (_tmp23_);
	_g_free0 (_tmp21_);
	_tmp24_ = self->priv->background;
	gtk_widget_show ((GtkWidget*) _tmp24_);
	_tmp25_ = self->priv->background;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp25_);
	_tmp26_ = self->priv->background;
	unity_greeter_add_style_class ((GtkWidget*) _tmp26_);
	_tmp27_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp27_);
	_g_object_unref0 (self->priv->login_box);
	self->priv->login_box = _tmp27_;
	_tmp28_ = self->priv->login_box;
	gtk_widget_show ((GtkWidget*) _tmp28_);
	_tmp29_ = self->priv->background;
	_tmp30_ = self->priv->login_box;
	gtk_container_add ((GtkContainer*) _tmp29_, (GtkWidget*) _tmp30_);
	_tmp31_ = (GtkHButtonBox*) gtk_hbutton_box_new ();
	g_object_ref_sink (_tmp31_);
	buttonbox = _tmp31_;
	_tmp32_ = buttonbox;
	gtk_button_box_set_layout ((GtkButtonBox*) _tmp32_, GTK_BUTTONBOX_END);
	_tmp33_ = buttonbox;
	gtk_box_set_spacing ((GtkBox*) _tmp33_, -1);
	_tmp34_ = g_strdup ("");
	shadow_style = _tmp34_;
	{
		GtkCssProvider* style = NULL;
		GtkCssProvider* _tmp35_ = NULL;
		GtkCssProvider* _tmp36_ = NULL;
		const gchar* _tmp37_ = NULL;
		gchar* _tmp38_ = NULL;
		gchar* _tmp39_ = NULL;
		GtkStyleContext* context = NULL;
		GtkHButtonBox* _tmp40_ = NULL;
		GtkStyleContext* _tmp41_ = NULL;
		GtkStyleContext* _tmp42_ = NULL;
		GtkStyleContext* _tmp43_ = NULL;
		GtkCssProvider* _tmp44_ = NULL;
		_tmp35_ = gtk_css_provider_new ();
		style = _tmp35_;
		_tmp36_ = style;
		_tmp37_ = shadow_style;
		_tmp38_ = g_strdup_printf ("* {background-color: transparent;\n" \
"                                      %s\n" \
"                                     }", _tmp37_);
		_tmp39_ = _tmp38_;
		gtk_css_provider_load_from_data (_tmp36_, _tmp39_, (gssize) (-1), &_inner_error_);
		_g_free0 (_tmp39_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (style);
			goto __catch12_g_error;
		}
		_tmp40_ = buttonbox;
		_tmp41_ = gtk_widget_get_style_context ((GtkWidget*) _tmp40_);
		_tmp42_ = _g_object_ref0 (_tmp41_);
		context = _tmp42_;
		_tmp43_ = context;
		_tmp44_ = style;
		gtk_style_context_add_provider (_tmp43_, (GtkStyleProvider*) _tmp44_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
		_g_object_unref0 (context);
		_g_object_unref0 (style);
	}
	goto __finally12;
	__catch12_g_error:
	{
		GError* e = NULL;
		GError* _tmp45_ = NULL;
		const gchar* _tmp46_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp45_ = e;
		_tmp46_ = _tmp45_->message;
		g_debug ("main-window.vala:89: Internal error loading buttonbox style: %s", _tmp46_);
		_g_error_free0 (e);
	}
	__finally12:
	if (_inner_error_ != NULL) {
		_g_free0 (shadow_style);
		_g_object_unref0 (buttonbox);
		_g_object_unref0 (accel_group);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
	}
	_tmp47_ = buttonbox;
	gtk_widget_set_size_request ((GtkWidget*) _tmp47_, -1, MAIN_WINDOW_BUTTONBOX_HEIGHT);
	_tmp48_ = buttonbox;
	gtk_widget_show ((GtkWidget*) _tmp48_);
	_tmp49_ = (GtkAlignment*) gtk_alignment_new (1.0f, 1.0f, 0.0f, 0.0f);
	g_object_ref_sink (_tmp49_);
	buttonbox_align = _tmp49_;
	_tmp50_ = buttonbox_align;
	gtk_widget_show ((GtkWidget*) _tmp50_);
	_tmp51_ = self->priv->login_box;
	_tmp52_ = buttonbox_align;
	gtk_container_add ((GtkContainer*) _tmp51_, (GtkWidget*) _tmp52_);
	_tmp53_ = buttonbox_align;
	_tmp54_ = buttonbox;
	gtk_container_add ((GtkContainer*) _tmp53_, (GtkWidget*) _tmp54_);
	_tmp55_ = buttonbox;
	unity_greeter_add_style_class ((GtkWidget*) _tmp55_);
	_tmp56_ = (GtkAlignment*) gtk_alignment_new (1.0f, 1.0f, 0.0f, 0.0f);
	g_object_ref_sink (_tmp56_);
	a11yalign = _tmp56_;
	_tmp57_ = a11yalign;
	gtk_widget_show ((GtkWidget*) _tmp57_);
	_tmp58_ = buttonbox;
	_tmp59_ = a11yalign;
	gtk_container_add ((GtkContainer*) _tmp58_, (GtkWidget*) _tmp59_);
	_tmp60_ = (GtkToggleButton*) gtk_toggle_button_new ();
	g_object_ref_sink (_tmp60_);
	_g_object_unref0 (self->priv->a11ybutton);
	self->priv->a11ybutton = _tmp60_;
	_tmp61_ = self->priv->a11ybutton;
	gtk_widget_show ((GtkWidget*) _tmp61_);
	_tmp62_ = g_build_filename (PKGDATADIR, "keyboardbutton.png", NULL);
	_tmp63_ = _tmp62_;
	_tmp64_ = (GtkImage*) gtk_image_new_from_file (_tmp63_);
	g_object_ref_sink (_tmp64_);
	_tmp65_ = _tmp64_;
	_g_free0 (_tmp63_);
	a11ybuttonimage = _tmp65_;
	_tmp66_ = a11ybuttonimage;
	gtk_widget_show ((GtkWidget*) _tmp66_);
	_tmp67_ = self->priv->a11ybutton;
	_tmp68_ = a11ybuttonimage;
	gtk_container_add ((GtkContainer*) _tmp67_, (GtkWidget*) _tmp68_);
	_tmp69_ = self->priv->a11ybutton;
	g_signal_connect_object (_tmp69_, "toggled", (GCallback) _main_window_keyboardbutton_clicked_cb_gtk_toggle_button_toggled, self, 0);
	_tmp70_ = a11yalign;
	_tmp71_ = self->priv->a11ybutton;
	gtk_container_add ((GtkContainer*) _tmp70_, (GtkWidget*) _tmp71_);
	_tmp72_ = self->priv->a11ybutton;
	unity_greeter_add_style_class ((GtkWidget*) _tmp72_);
	_tmp73_ = (GtkAlignment*) gtk_alignment_new (0.5f, 1.0f, 0.0f, 0.0f);
	g_object_ref_sink (_tmp73_);
	shutdownbutton_align = _tmp73_;
	_tmp74_ = shutdownbutton_align;
	gtk_widget_show ((GtkWidget*) _tmp74_);
	_tmp75_ = buttonbox;
	_tmp76_ = shutdownbutton_align;
	gtk_container_add ((GtkContainer*) _tmp75_, (GtkWidget*) _tmp76_);
	_tmp77_ = shutdownbutton_align;
	unity_greeter_add_style_class ((GtkWidget*) _tmp77_);
	_tmp78_ = (GtkButton*) gtk_button_new ();
	g_object_ref_sink (_tmp78_);
	_g_object_unref0 (self->priv->shutdownbutton);
	self->priv->shutdownbutton = _tmp78_;
	_tmp79_ = self->priv->shutdownbutton;
	gtk_widget_show ((GtkWidget*) _tmp79_);
	_tmp80_ = g_build_filename (PKGDATADIR, "shutdownbutton.png", NULL);
	_tmp81_ = _tmp80_;
	_tmp82_ = (GtkImage*) gtk_image_new_from_file (_tmp81_);
	g_object_ref_sink (_tmp82_);
	_tmp83_ = _tmp82_;
	_g_free0 (_tmp81_);
	shutdownbutton_image = _tmp83_;
	_tmp84_ = shutdownbutton_image;
	gtk_widget_show ((GtkWidget*) _tmp84_);
	_tmp85_ = self->priv->shutdownbutton;
	_tmp86_ = shutdownbutton_image;
	gtk_container_add ((GtkContainer*) _tmp85_, (GtkWidget*) _tmp86_);
	_tmp87_ = self->priv->shutdownbutton;
	g_signal_connect_object (_tmp87_, "clicked", (GCallback) _main_window_shutdownbutton_clicked_cb_gtk_button_clicked, self, 0);
	_tmp88_ = shutdownbutton_align;
	_tmp89_ = self->priv->shutdownbutton;
	gtk_container_add ((GtkContainer*) _tmp88_, (GtkWidget*) _tmp89_);
	_tmp90_ = self->priv->shutdownbutton;
	unity_greeter_add_style_class ((GtkWidget*) _tmp90_);
	_tmp91_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp91_);
	_g_object_unref0 (self->priv->hbox);
	self->priv->hbox = _tmp91_;
	_tmp92_ = self->priv->hbox;
	g_object_set ((GtkWidget*) _tmp92_, "expand", TRUE, NULL);
	_tmp93_ = self->priv->hbox;
	gtk_widget_show ((GtkWidget*) _tmp93_);
	_tmp94_ = self->priv->login_box;
	_tmp95_ = self->priv->hbox;
	gtk_container_add ((GtkContainer*) _tmp94_, (GtkWidget*) _tmp95_);
	_tmp96_ = (GtkAlignment*) gtk_alignment_new (0.5f, 0.5f, 0.0f, 0.0f);
	g_object_ref_sink (_tmp96_);
	align = _tmp96_;
	_tmp97_ = align;
	gtk_widget_set_size_request ((GtkWidget*) _tmp97_, grid_size, -1);
	_tmp98_ = align;
	gtk_widget_set_margin_bottom ((GtkWidget*) _tmp98_, MAIN_WINDOW_BUTTONBOX_HEIGHT);
	_tmp99_ = align;
	gtk_widget_show ((GtkWidget*) _tmp99_);
	_tmp100_ = self->priv->hbox;
	_tmp101_ = align;
	gtk_container_add ((GtkContainer*) _tmp100_, (GtkWidget*) _tmp101_);
	_tmp102_ = flat_button_new ();
	g_object_ref_sink (_tmp102_);
	_g_object_unref0 (self->priv->back_button);
	self->priv->back_button = (GtkButton*) _tmp102_;
	_tmp103_ = self->priv->back_button;
	_tmp104_ = gtk_widget_get_accessible ((GtkWidget*) _tmp103_);
	_tmp105_ = _ ("Back");
	atk_object_set_name (_tmp104_, _tmp105_);
	_tmp106_ = self->priv->back_button;
	gtk_button_set_focus_on_click (_tmp106_, FALSE);
	_tmp107_ = g_build_filename (PKGDATADIR, "arrow_left.png", NULL, NULL);
	_tmp108_ = _tmp107_;
	_tmp109_ = (GtkImage*) gtk_image_new_from_file (_tmp108_);
	g_object_ref_sink (_tmp109_);
	_tmp110_ = _tmp109_;
	_g_free0 (_tmp108_);
	image = _tmp110_;
	_tmp111_ = image;
	gtk_widget_show ((GtkWidget*) _tmp111_);
	_tmp112_ = self->priv->back_button;
	gtk_widget_set_size_request ((GtkWidget*) _tmp112_, grid_size - (GREETER_LIST_BORDER * 2), grid_size - (GREETER_LIST_BORDER * 2));
	_tmp113_ = self->priv->back_button;
	_tmp114_ = image;
	gtk_container_add ((GtkContainer*) _tmp113_, (GtkWidget*) _tmp114_);
	_tmp115_ = self->priv->back_button;
	g_signal_connect_object (_tmp115_, "clicked", (GCallback) _main_window_pop_list_gtk_button_clicked, self, 0);
	_tmp116_ = align;
	_tmp117_ = self->priv->back_button;
	gtk_container_add ((GtkContainer*) _tmp116_, (GtkWidget*) _tmp117_);
	_tmp118_ = (GtkAlignment*) gtk_alignment_new (0.0f, 0.5f, 0.0f, 1.0f);
	g_object_ref_sink (_tmp118_);
	_g_object_unref0 (align);
	align = _tmp118_;
	_tmp119_ = align;
	gtk_widget_show ((GtkWidget*) _tmp119_);
	_tmp120_ = self->priv->hbox;
	_tmp121_ = align;
	gtk_container_add ((GtkContainer*) _tmp120_, (GtkWidget*) _tmp121_);
	_tmp122_ = list_stack_new ();
	g_object_ref_sink (_tmp122_);
	_g_object_unref0 (self->stack);
	self->stack = _tmp122_;
	_tmp123_ = self->stack;
	gtk_widget_show ((GtkWidget*) _tmp123_);
	_tmp124_ = align;
	_tmp125_ = self->stack;
	gtk_container_add ((GtkContainer*) _tmp124_, (GtkWidget*) _tmp125_);
	main_window_add_user_list (self);
	_tmp126_ = unity_greeter_singleton;
	_tmp127_ = _tmp126_->test_mode;
	if (_tmp127_) {
		Monitor* _tmp128_ = NULL;
		Monitor* _tmp129_ = NULL;
		Background* _tmp130_ = NULL;
		GList* _tmp131_ = NULL;
		GList* _tmp132_ = NULL;
		gconstpointer _tmp133_ = NULL;
		__g_list_free__monitor_unref0_0 (self->priv->monitors);
		self->priv->monitors = NULL;
		_tmp128_ = monitor_new (0, 0, 800, 600);
		self->priv->monitors = g_list_append (self->priv->monitors, _tmp128_);
		_tmp129_ = monitor_new (800, 120, 640, 480);
		self->priv->monitors = g_list_append (self->priv->monitors, _tmp129_);
		_tmp130_ = self->priv->background;
		_tmp131_ = self->priv->monitors;
		background_set_monitors (_tmp130_, _tmp131_);
		_tmp132_ = self->priv->monitors;
		_tmp133_ = g_list_nth_data (_tmp132_, (guint) 0);
		main_window_move_to_monitor (self, (Monitor*) _tmp133_);
		gtk_window_resize ((GtkWindow*) self, 800 + 640, 600);
	} else {
		GdkScreen* screen = NULL;
		GdkScreen* _tmp134_ = NULL;
		GdkScreen* _tmp135_ = NULL;
		GdkScreen* _tmp136_ = NULL;
		GdkScreen* _tmp137_ = NULL;
		_tmp134_ = gtk_window_get_screen ((GtkWindow*) self);
		_tmp135_ = _g_object_ref0 (_tmp134_);
		screen = _tmp135_;
		_tmp136_ = screen;
		g_signal_connect_object (_tmp136_, "monitors-changed", (GCallback) _main_window_monitors_changed_cb_gdk_screen_monitors_changed, self, 0);
		_tmp137_ = screen;
		main_window_monitors_changed_cb (self, _tmp137_);
		_g_object_unref0 (screen);
	}
	_g_object_unref0 (image);
	_g_object_unref0 (align);
	_g_object_unref0 (shutdownbutton_image);
	_g_object_unref0 (shutdownbutton_align);
	_g_object_unref0 (a11ybuttonimage);
	_g_object_unref0 (a11yalign);
	_g_object_unref0 (buttonbox_align);
	_g_free0 (shadow_style);
	_g_object_unref0 (buttonbox);
	_g_object_unref0 (accel_group);
	return obj;
}


static void main_window_class_init (MainWindowClass * klass) {
	main_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainWindowPrivate));
	GTK_WIDGET_CLASS (klass)->size_allocate = main_window_real_size_allocate;
	GTK_WIDGET_CLASS (klass)->motion_notify_event = main_window_real_motion_notify_event;
	GTK_WIDGET_CLASS (klass)->key_press_event = main_window_real_key_press_event;
	G_OBJECT_CLASS (klass)->get_property = _vala_main_window_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_main_window_set_property;
	G_OBJECT_CLASS (klass)->constructor = main_window_constructor;
	G_OBJECT_CLASS (klass)->finalize = main_window_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIN_WINDOW_KEYBOARD_WINDOW, g_param_spec_object ("keyboard-window", "keyboard-window", "keyboard-window", GTK_TYPE_WINDOW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void main_window_instance_init (MainWindow * self) {
	self->priv = MAIN_WINDOW_GET_PRIVATE (self);
	self->priv->shutdown_dialog = NULL;
	self->priv->_keyboard_window = NULL;
	self->priv->keyboard_pid = (GPid) 0;
}


static void main_window_finalize (GObject* obj) {
	MainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN_WINDOW, MainWindow);
	__g_list_free__monitor_unref0_0 (self->priv->monitors);
	_monitor_unref0 (self->priv->primary_monitor);
	_monitor_unref0 (self->priv->active_monitor);
	_g_object_unref0 (self->priv->background);
	_g_object_unref0 (self->priv->login_box);
	_g_object_unref0 (self->priv->hbox);
	_g_object_unref0 (self->priv->back_button);
	_g_object_unref0 (self->priv->shutdown_dialog);
	_g_object_unref0 (self->stack);
	_g_object_unref0 (self->priv->_keyboard_window);
	_g_object_unref0 (self->priv->shutdownbutton);
	_g_object_unref0 (self->priv->a11ybutton);
	G_OBJECT_CLASS (main_window_parent_class)->finalize (obj);
}


GType main_window_get_type (void) {
	static volatile gsize main_window_type_id__volatile = 0;
	if (g_once_init_enter (&main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainWindow), 0, (GInstanceInitFunc) main_window_instance_init, NULL };
		GType main_window_type_id;
		main_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "MainWindow", &g_define_type_info, 0);
		g_once_init_leave (&main_window_type_id__volatile, main_window_type_id);
	}
	return main_window_type_id__volatile;
}


static void _vala_main_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MAIN_WINDOW, MainWindow);
	switch (property_id) {
		case MAIN_WINDOW_KEYBOARD_WINDOW:
		g_value_set_object (value, main_window_get_keyboard_window (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_main_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MAIN_WINDOW, MainWindow);
	switch (property_id) {
		case MAIN_WINDOW_KEYBOARD_WINDOW:
		main_window_set_keyboard_window (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



