/* settings-daemon.c generated by valac 0.22.1, the Vala compiler
 * generated from settings-daemon.vala, do not modify */

/* -*- Mode:Vala; indent-tabs-mode:nil; tab-width:4 -*-
 *
 * Copyright (C) 2011 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by: Michael Terry <michael.terry@canonical.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gunixfdlist.h>
#include "config.h"
#include "libgnome-desktop/gnome-idle-monitor.h"


#define TYPE_SETTINGS_DAEMON (settings_daemon_get_type ())
#define SETTINGS_DAEMON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SETTINGS_DAEMON, SettingsDaemon))
#define SETTINGS_DAEMON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SETTINGS_DAEMON, SettingsDaemonClass))
#define IS_SETTINGS_DAEMON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SETTINGS_DAEMON))
#define IS_SETTINGS_DAEMON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SETTINGS_DAEMON))
#define SETTINGS_DAEMON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SETTINGS_DAEMON, SettingsDaemonClass))

typedef struct _SettingsDaemon SettingsDaemon;
typedef struct _SettingsDaemonClass SettingsDaemonClass;
typedef struct _SettingsDaemonPrivate SettingsDaemonPrivate;

#define TYPE_SCREEN_SAVER_INTERFACE (screen_saver_interface_get_type ())
#define SCREEN_SAVER_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCREEN_SAVER_INTERFACE, ScreenSaverInterface))
#define SCREEN_SAVER_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCREEN_SAVER_INTERFACE, ScreenSaverInterfaceClass))
#define IS_SCREEN_SAVER_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCREEN_SAVER_INTERFACE))
#define IS_SCREEN_SAVER_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCREEN_SAVER_INTERFACE))
#define SCREEN_SAVER_INTERFACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCREEN_SAVER_INTERFACE, ScreenSaverInterfaceClass))

typedef struct _ScreenSaverInterface ScreenSaverInterface;
typedef struct _ScreenSaverInterfaceClass ScreenSaverInterfaceClass;

#define TYPE_SESSION_MANAGER_INTERFACE (session_manager_interface_get_type ())
#define SESSION_MANAGER_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SESSION_MANAGER_INTERFACE, SessionManagerInterface))
#define SESSION_MANAGER_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SESSION_MANAGER_INTERFACE, SessionManagerInterfaceClass))
#define IS_SESSION_MANAGER_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SESSION_MANAGER_INTERFACE))
#define IS_SESSION_MANAGER_INTERFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SESSION_MANAGER_INTERFACE))
#define SESSION_MANAGER_INTERFACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SESSION_MANAGER_INTERFACE, SessionManagerInterfaceClass))

typedef struct _SessionManagerInterface SessionManagerInterface;
typedef struct _SessionManagerInterfaceClass SessionManagerInterfaceClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_variant_type_free0(var) ((var == NULL) ? NULL : (var = (g_variant_type_free (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_settings_schema_unref0(var) ((var == NULL) ? NULL : (var = (g_settings_schema_unref (var), NULL)))
#define _g_settings_schema_source_unref0(var) ((var == NULL) ? NULL : (var = (g_settings_schema_source_unref (var), NULL)))
typedef struct _ScreenSaverInterfacePrivate ScreenSaverInterfacePrivate;
typedef struct _SessionManagerInterfacePrivate SessionManagerInterfacePrivate;

struct _SettingsDaemon {
	GObject parent_instance;
	SettingsDaemonPrivate * priv;
};

struct _SettingsDaemonClass {
	GObjectClass parent_class;
};

struct _SettingsDaemonPrivate {
	gint logind_inhibit_fd;
	ScreenSaverInterface* screen_saver;
	SessionManagerInterface* session_manager;
	gint n_names;
};

struct _ScreenSaverInterface {
	GObject parent_instance;
	ScreenSaverInterfacePrivate * priv;
};

struct _ScreenSaverInterfaceClass {
	GObjectClass parent_class;
};

struct _ScreenSaverInterfacePrivate {
	GnomeIdleMonitor* idle_monitor;
	gboolean _active;
	guint idle_watch;
};

struct _SessionManagerInterface {
	GObject parent_instance;
	SessionManagerInterfacePrivate * priv;
};

struct _SessionManagerInterfaceClass {
	GObjectClass parent_class;
};


static gpointer settings_daemon_parent_class = NULL;
static gpointer screen_saver_interface_parent_class = NULL;
static gpointer session_manager_interface_parent_class = NULL;

GType settings_daemon_get_type (void) G_GNUC_CONST;
GType screen_saver_interface_get_type (void) G_GNUC_CONST;
guint screen_saver_interface_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType session_manager_interface_get_type (void) G_GNUC_CONST;
guint session_manager_interface_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
#define SETTINGS_DAEMON_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SETTINGS_DAEMON, SettingsDaemonPrivate))
enum  {
	SETTINGS_DAEMON_DUMMY_PROPERTY
};
void settings_daemon_start (SettingsDaemon* self);
static void settings_daemon_set_plugin_enabled (SettingsDaemon* self, const gchar* schema_name, gboolean enabled);
SessionManagerInterface* session_manager_interface_new (void);
SessionManagerInterface* session_manager_interface_construct (GType object_type);
static void __lambda9_ (SettingsDaemon* self, GDBusConnection* c);
static void ___lambda9__gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void __lambda10_ (SettingsDaemon* self);
static void settings_daemon_start_settings_daemon (SettingsDaemon* self);
static void ___lambda10__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void __lambda11_ (SettingsDaemon* self);
static void ___lambda11__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self);
ScreenSaverInterface* screen_saver_interface_new (void);
ScreenSaverInterface* screen_saver_interface_construct (GType object_type);
static void __lambda12_ (SettingsDaemon* self, GDBusConnection* c);
static void ___lambda12__gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void __lambda13_ (SettingsDaemon* self);
static void ___lambda13__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void __lambda14_ (SettingsDaemon* self);
static void ___lambda14__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self);
SettingsDaemon* settings_daemon_new (void);
SettingsDaemon* settings_daemon_construct (GType object_type);
static void settings_daemon_finalize (GObject* obj);
#define SCREEN_SAVER_INTERFACE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SCREEN_SAVER_INTERFACE, ScreenSaverInterfacePrivate))
enum  {
	SCREEN_SAVER_INTERFACE_DUMMY_PROPERTY
};
static void _screen_saver_interface_set_active (ScreenSaverInterface* self, gboolean value);
static void ___lambda7_ (ScreenSaverInterface* self);
void screen_saver_interface_set_active (ScreenSaverInterface* self, gboolean value);
static void ____lambda7__gnome_idle_monitor_watch_func (GnomeIdleMonitor* monitor, guint id, gpointer self);
gint ug_settings_get_integer (const gchar* key);
#define UG_SETTINGS_KEY_IDLE_TIMEOUT "idle-timeout"
static void ____lambda8_ (ScreenSaverInterface* self);
static void _____lambda8__gnome_idle_monitor_watch_func (GnomeIdleMonitor* monitor, guint id, gpointer self);
gboolean screen_saver_interface_get_active (ScreenSaverInterface* self);
guint32 screen_saver_interface_get_active_time (ScreenSaverInterface* self);
void screen_saver_interface_lock (ScreenSaverInterface* self);
void screen_saver_interface_show_message (ScreenSaverInterface* self, const gchar* summary, const gchar* body, const gchar* icon);
void screen_saver_interface_simulate_user_activity (ScreenSaverInterface* self);
static void screen_saver_interface_finalize (GObject* obj);
static void _dbus_screen_saver_interface_set_active (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_screen_saver_interface_get_active (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_screen_saver_interface_get_active_time (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_screen_saver_interface_lock (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_screen_saver_interface_show_message (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_screen_saver_interface_simulate_user_activity (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void screen_saver_interface_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* screen_saver_interface_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean screen_saver_interface_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_screen_saver_interface_active_changed (GObject* _sender, gboolean value, gpointer* _data);
static void _screen_saver_interface_unregister_object (gpointer user_data);
enum  {
	SESSION_MANAGER_INTERFACE_DUMMY_PROPERTY,
	SESSION_MANAGER_INTERFACE_SESSION_IS_ACTIVE,
	SESSION_MANAGER_INTERFACE_SESSION_NAME,
	SESSION_MANAGER_INTERFACE_INHIBITED_ACTIONS
};
gboolean session_manager_interface_get_session_is_active (SessionManagerInterface* self);
const gchar* session_manager_interface_get_session_name (SessionManagerInterface* self);
guint32 session_manager_interface_get_inhibited_actions (SessionManagerInterface* self);
static void _vala_session_manager_interface_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void session_manager_interface_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* session_manager_interface_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static GVariant* _dbus_session_manager_interface_get_session_is_active (SessionManagerInterface* self);
static GVariant* _dbus_session_manager_interface_get_session_name (SessionManagerInterface* self);
static GVariant* _dbus_session_manager_interface_get_inhibited_actions (SessionManagerInterface* self);
static gboolean session_manager_interface_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _session_manager_interface_unregister_object (gpointer user_data);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

static const GDBusArgInfo _screen_saver_interface_dbus_arg_info_set_active_value = {-1, "value", "b"};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_set_active_in[] = {&_screen_saver_interface_dbus_arg_info_set_active_value, NULL};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_set_active_out[] = {NULL};
static const GDBusMethodInfo _screen_saver_interface_dbus_method_info_set_active = {-1, "SetActive", (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_set_active_in), (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_set_active_out)};
static const GDBusArgInfo _screen_saver_interface_dbus_arg_info_get_active_result = {-1, "result", "b"};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_get_active_in[] = {NULL};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_get_active_out[] = {&_screen_saver_interface_dbus_arg_info_get_active_result, NULL};
static const GDBusMethodInfo _screen_saver_interface_dbus_method_info_get_active = {-1, "GetActive", (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_get_active_in), (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_get_active_out)};
static const GDBusArgInfo _screen_saver_interface_dbus_arg_info_get_active_time_result = {-1, "result", "u"};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_get_active_time_in[] = {NULL};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_get_active_time_out[] = {&_screen_saver_interface_dbus_arg_info_get_active_time_result, NULL};
static const GDBusMethodInfo _screen_saver_interface_dbus_method_info_get_active_time = {-1, "GetActiveTime", (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_get_active_time_in), (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_get_active_time_out)};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_lock_in[] = {NULL};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_lock_out[] = {NULL};
static const GDBusMethodInfo _screen_saver_interface_dbus_method_info_lock = {-1, "Lock", (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_lock_in), (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_lock_out)};
static const GDBusArgInfo _screen_saver_interface_dbus_arg_info_show_message_summary = {-1, "summary", "s"};
static const GDBusArgInfo _screen_saver_interface_dbus_arg_info_show_message_body = {-1, "body", "s"};
static const GDBusArgInfo _screen_saver_interface_dbus_arg_info_show_message_icon = {-1, "icon", "s"};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_show_message_in[] = {&_screen_saver_interface_dbus_arg_info_show_message_summary, &_screen_saver_interface_dbus_arg_info_show_message_body, &_screen_saver_interface_dbus_arg_info_show_message_icon, NULL};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_show_message_out[] = {NULL};
static const GDBusMethodInfo _screen_saver_interface_dbus_method_info_show_message = {-1, "ShowMessage", (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_show_message_in), (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_show_message_out)};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_simulate_user_activity_in[] = {NULL};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_simulate_user_activity_out[] = {NULL};
static const GDBusMethodInfo _screen_saver_interface_dbus_method_info_simulate_user_activity = {-1, "SimulateUserActivity", (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_simulate_user_activity_in), (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_simulate_user_activity_out)};
static const GDBusMethodInfo * const _screen_saver_interface_dbus_method_info[] = {&_screen_saver_interface_dbus_method_info_set_active, &_screen_saver_interface_dbus_method_info_get_active, &_screen_saver_interface_dbus_method_info_get_active_time, &_screen_saver_interface_dbus_method_info_lock, &_screen_saver_interface_dbus_method_info_show_message, &_screen_saver_interface_dbus_method_info_simulate_user_activity, NULL};
static const GDBusArgInfo _screen_saver_interface_dbus_arg_info_active_changed_value = {-1, "value", "b"};
static const GDBusArgInfo * const _screen_saver_interface_dbus_arg_info_active_changed[] = {&_screen_saver_interface_dbus_arg_info_active_changed_value, NULL};
static const GDBusSignalInfo _screen_saver_interface_dbus_signal_info_active_changed = {-1, "ActiveChanged", (GDBusArgInfo **) (&_screen_saver_interface_dbus_arg_info_active_changed)};
static const GDBusSignalInfo * const _screen_saver_interface_dbus_signal_info[] = {&_screen_saver_interface_dbus_signal_info_active_changed, NULL};
static const GDBusPropertyInfo * const _screen_saver_interface_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _screen_saver_interface_dbus_interface_info = {-1, "org.gnome.ScreenSaver", (GDBusMethodInfo **) (&_screen_saver_interface_dbus_method_info), (GDBusSignalInfo **) (&_screen_saver_interface_dbus_signal_info), (GDBusPropertyInfo **) (&_screen_saver_interface_dbus_property_info)};
static const GDBusInterfaceVTable _screen_saver_interface_dbus_interface_vtable = {screen_saver_interface_dbus_interface_method_call, screen_saver_interface_dbus_interface_get_property, screen_saver_interface_dbus_interface_set_property};
static const GDBusMethodInfo * const _session_manager_interface_dbus_method_info[] = {NULL};
static const GDBusSignalInfo * const _session_manager_interface_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo _session_manager_interface_dbus_property_info_session_is_active = {-1, "SessionIsActive", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _session_manager_interface_dbus_property_info_session_name = {-1, "SessionName", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _session_manager_interface_dbus_property_info_inhibited_actions = {-1, "InhibitedActions", "u", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo * const _session_manager_interface_dbus_property_info[] = {&_session_manager_interface_dbus_property_info_session_is_active, &_session_manager_interface_dbus_property_info_session_name, &_session_manager_interface_dbus_property_info_inhibited_actions, NULL};
static const GDBusInterfaceInfo _session_manager_interface_dbus_interface_info = {-1, "org.gnome.SessionManager", (GDBusMethodInfo **) (&_session_manager_interface_dbus_method_info), (GDBusSignalInfo **) (&_session_manager_interface_dbus_signal_info), (GDBusPropertyInfo **) (&_session_manager_interface_dbus_property_info)};
static const GDBusInterfaceVTable _session_manager_interface_dbus_interface_vtable = {session_manager_interface_dbus_interface_method_call, session_manager_interface_dbus_interface_get_property, session_manager_interface_dbus_interface_set_property};

static void __lambda9_ (SettingsDaemon* self, GDBusConnection* c) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (c != NULL);
	{
		GDBusConnection* _tmp0_ = NULL;
		SessionManagerInterface* _tmp1_ = NULL;
		_tmp0_ = c;
		_tmp1_ = self->priv->session_manager;
		session_manager_interface_register_object (_tmp1_, _tmp0_, "/org/gnome/SessionManager", &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch17_g_error;
		}
	}
	goto __finally17;
	__catch17_g_error:
	{
		GError* e = NULL;
		GError* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = e;
		_tmp3_ = _tmp2_->message;
		g_warning ("settings-daemon.vala:70: Failed to register /org/gnome/SessionManager:" \
" %s", _tmp3_);
		_g_error_free0 (e);
	}
	__finally17:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void ___lambda9__gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda9_ (self, connection);
}


static void __lambda10_ (SettingsDaemon* self) {
	g_debug ("settings-daemon.vala:75: Acquired org.gnome.SessionManager");
	settings_daemon_start_settings_daemon (self);
}


static void ___lambda10__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda10_ (self);
}


static void __lambda11_ (SettingsDaemon* self) {
	g_debug ("settings-daemon.vala:78: Failed to acquire name org.gnome.SessionManag" \
"er");
}


static void ___lambda11__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda11_ (self);
}


static void __lambda12_ (SettingsDaemon* self, GDBusConnection* c) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (c != NULL);
	{
		GDBusConnection* _tmp0_ = NULL;
		ScreenSaverInterface* _tmp1_ = NULL;
		_tmp0_ = c;
		_tmp1_ = self->priv->screen_saver;
		screen_saver_interface_register_object (_tmp1_, _tmp0_, "/org/gnome/ScreenSaver", &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch18_g_error;
		}
	}
	goto __finally18;
	__catch18_g_error:
	{
		GError* e = NULL;
		GError* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = e;
		_tmp3_ = _tmp2_->message;
		g_warning ("settings-daemon.vala:97: Failed to register /org/gnome/ScreenSaver: %s", _tmp3_);
		_g_error_free0 (e);
	}
	__finally18:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void ___lambda12__gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda12_ (self, connection);
}


static void __lambda13_ (SettingsDaemon* self) {
	g_debug ("settings-daemon.vala:102: Acquired org.gnome.ScreenSaver");
	settings_daemon_start_settings_daemon (self);
}


static void ___lambda13__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda13_ (self);
}


static void __lambda14_ (SettingsDaemon* self) {
	g_debug ("settings-daemon.vala:105: Failed to acquire name org.gnome.ScreenSaver");
}


static void ___lambda14__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda14_ (self);
}


void settings_daemon_start (SettingsDaemon* self) {
	gchar** disabled = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar** _tmp14_ = NULL;
	gint disabled_length1 = 0;
	gint _disabled_size_ = 0;
	gchar** enabled = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gint enabled_length1 = 0;
	gint _enabled_size_ = 0;
	gchar** _tmp23_ = NULL;
	gint _tmp23__length1 = 0;
	gchar** _tmp26_ = NULL;
	gint _tmp26__length1 = 0;
	SessionManagerInterface* _tmp29_ = NULL;
	gint _tmp30_ = 0;
	ScreenSaverInterface* _tmp31_ = NULL;
	gint _tmp32_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("org.gnome.settings-daemon.plugins.background");
	_tmp1_ = g_strdup ("org.gnome.settings-daemon.plugins.clipboard");
	_tmp2_ = g_strdup ("org.gnome.settings-daemon.plugins.font");
	_tmp3_ = g_strdup ("org.gnome.settings-daemon.plugins.gconf");
	_tmp4_ = g_strdup ("org.gnome.settings-daemon.plugins.gsdwacom");
	_tmp5_ = g_strdup ("org.gnome.settings-daemon.plugins.housekeeping");
	_tmp6_ = g_strdup ("org.gnome.settings-daemon.plugins.keybindings");
	_tmp7_ = g_strdup ("org.gnome.settings-daemon.plugins.keyboard");
	_tmp8_ = g_strdup ("org.gnome.settings-daemon.plugins.media-keys");
	_tmp9_ = g_strdup ("org.gnome.settings-daemon.plugins.mouse");
	_tmp10_ = g_strdup ("org.gnome.settings-daemon.plugins.print-notifications");
	_tmp11_ = g_strdup ("org.gnome.settings-daemon.plugins.smartcard");
	_tmp12_ = g_strdup ("org.gnome.settings-daemon.plugins.sound");
	_tmp13_ = g_strdup ("org.gnome.settings-daemon.plugins.wacom");
	_tmp14_ = g_new0 (gchar*, 14 + 1);
	_tmp14_[0] = _tmp0_;
	_tmp14_[1] = _tmp1_;
	_tmp14_[2] = _tmp2_;
	_tmp14_[3] = _tmp3_;
	_tmp14_[4] = _tmp4_;
	_tmp14_[5] = _tmp5_;
	_tmp14_[6] = _tmp6_;
	_tmp14_[7] = _tmp7_;
	_tmp14_[8] = _tmp8_;
	_tmp14_[9] = _tmp9_;
	_tmp14_[10] = _tmp10_;
	_tmp14_[11] = _tmp11_;
	_tmp14_[12] = _tmp12_;
	_tmp14_[13] = _tmp13_;
	disabled = _tmp14_;
	disabled_length1 = 14;
	_disabled_size_ = disabled_length1;
	_tmp15_ = g_strdup ("org.gnome.settings-daemon.plugins.a11y-keyboard");
	_tmp16_ = g_strdup ("org.gnome.settings-daemon.plugins.a11y-settings");
	_tmp17_ = g_strdup ("org.gnome.settings-daemon.plugins.color");
	_tmp18_ = g_strdup ("org.gnome.settings-daemon.plugins.cursor");
	_tmp19_ = g_strdup ("org.gnome.settings-daemon.plugins.power");
	_tmp20_ = g_strdup ("org.gnome.settings-daemon.plugins.xrandr");
	_tmp21_ = g_strdup ("org.gnome.settings-daemon.plugins.xsettings");
	_tmp22_ = g_new0 (gchar*, 7 + 1);
	_tmp22_[0] = _tmp15_;
	_tmp22_[1] = _tmp16_;
	_tmp22_[2] = _tmp17_;
	_tmp22_[3] = _tmp18_;
	_tmp22_[4] = _tmp19_;
	_tmp22_[5] = _tmp20_;
	_tmp22_[6] = _tmp21_;
	enabled = _tmp22_;
	enabled_length1 = 7;
	_enabled_size_ = enabled_length1;
	_tmp23_ = disabled;
	_tmp23__length1 = disabled_length1;
	{
		gchar** schema_collection = NULL;
		gint schema_collection_length1 = 0;
		gint _schema_collection_size_ = 0;
		gint schema_it = 0;
		schema_collection = _tmp23_;
		schema_collection_length1 = _tmp23__length1;
		for (schema_it = 0; schema_it < _tmp23__length1; schema_it = schema_it + 1) {
			gchar* _tmp24_ = NULL;
			gchar* schema = NULL;
			_tmp24_ = g_strdup (schema_collection[schema_it]);
			schema = _tmp24_;
			{
				const gchar* _tmp25_ = NULL;
				_tmp25_ = schema;
				settings_daemon_set_plugin_enabled (self, _tmp25_, FALSE);
				_g_free0 (schema);
			}
		}
	}
	_tmp26_ = enabled;
	_tmp26__length1 = enabled_length1;
	{
		gchar** schema_collection = NULL;
		gint schema_collection_length1 = 0;
		gint _schema_collection_size_ = 0;
		gint schema_it = 0;
		schema_collection = _tmp26_;
		schema_collection_length1 = _tmp26__length1;
		for (schema_it = 0; schema_it < _tmp26__length1; schema_it = schema_it + 1) {
			gchar* _tmp27_ = NULL;
			gchar* schema = NULL;
			_tmp27_ = g_strdup (schema_collection[schema_it]);
			schema = _tmp27_;
			{
				const gchar* _tmp28_ = NULL;
				_tmp28_ = schema;
				settings_daemon_set_plugin_enabled (self, _tmp28_, TRUE);
				_g_free0 (schema);
			}
		}
	}
	_tmp29_ = session_manager_interface_new ();
	_g_object_unref0 (self->priv->session_manager);
	self->priv->session_manager = _tmp29_;
	_tmp30_ = self->priv->n_names;
	self->priv->n_names = _tmp30_ + 1;
	g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, "org.gnome.SessionManager", G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) ((___lambda9__gbus_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda9__gbus_acquired_callback, g_object_ref (self), g_object_unref)), (GClosure*) ((___lambda10__gbus_name_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda10__gbus_name_acquired_callback, g_object_ref (self), g_object_unref)), (GClosure*) ((___lambda11__gbus_name_lost_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda11__gbus_name_lost_callback, g_object_ref (self), g_object_unref)));
	_tmp31_ = screen_saver_interface_new ();
	_g_object_unref0 (self->priv->screen_saver);
	self->priv->screen_saver = _tmp31_;
	_tmp32_ = self->priv->n_names;
	self->priv->n_names = _tmp32_ + 1;
	g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, "org.gnome.ScreenSaver", G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) ((___lambda12__gbus_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda12__gbus_acquired_callback, g_object_ref (self), g_object_unref)), (GClosure*) ((___lambda13__gbus_name_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda13__gbus_name_acquired_callback, g_object_ref (self), g_object_unref)), (GClosure*) ((___lambda14__gbus_name_lost_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda14__gbus_name_lost_callback, g_object_ref (self), g_object_unref)));
	{
		GDBusConnection* b = NULL;
		GDBusConnection* _tmp33_ = NULL;
		GUnixFDList* fd_list = NULL;
		GVariant* _result_ = NULL;
		GDBusConnection* _tmp34_ = NULL;
		const gchar* _tmp35_ = NULL;
		GVariant* _tmp36_ = NULL;
		GVariant* _tmp37_ = NULL;
		GVariantType* _tmp38_ = NULL;
		GVariantType* _tmp39_ = NULL;
		GUnixFDList* _tmp40_ = NULL;
		GVariant* _tmp41_ = NULL;
		GVariant* _tmp42_ = NULL;
		gint32 index = 0;
		GVariant* _tmp43_ = NULL;
		gint _tmp44_ = 0;
		GUnixFDList* _tmp45_ = NULL;
		gint32 _tmp46_ = 0;
		gint _tmp47_ = 0;
		_tmp33_ = g_bus_get_sync (G_BUS_TYPE_SYSTEM, NULL, &_inner_error_);
		b = _tmp33_;
		if (_inner_error_ != NULL) {
			goto __catch19_g_error;
		}
		_tmp34_ = b;
		_tmp35_ = g_get_user_name ();
		_tmp36_ = g_variant_new ("(ssss)", "handle-power-key", _tmp35_, "Unity Greeter handling keypresses", "block", NULL);
		g_variant_ref_sink (_tmp36_);
		_tmp37_ = _tmp36_;
		_tmp38_ = g_variant_type_new ("(h)");
		_tmp39_ = _tmp38_;
		_tmp41_ = g_dbus_connection_call_with_unix_fd_list_sync (_tmp34_, "org.freedesktop.login1", "/org/freedesktop/login1", "org.freedesktop.login1.Manager", "Inhibit", _tmp37_, _tmp39_, G_DBUS_CALL_FLAGS_NONE, -1, NULL, &_tmp40_, NULL, &_inner_error_);
		_g_object_unref0 (fd_list);
		fd_list = _tmp40_;
		_tmp42_ = _tmp41_;
		_g_variant_type_free0 (_tmp39_);
		_g_variant_unref0 (_tmp37_);
		_result_ = _tmp42_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (fd_list);
			_g_object_unref0 (b);
			goto __catch19_g_error;
		}
		index = (gint32) (-1);
		_tmp43_ = _result_;
		g_variant_get (_tmp43_, "(h)", &index, NULL);
		_tmp45_ = fd_list;
		_tmp46_ = index;
		_tmp47_ = g_unix_fd_list_get (_tmp45_, (gint) _tmp46_, &_inner_error_);
		_tmp44_ = _tmp47_;
		if (_inner_error_ != NULL) {
			_g_variant_unref0 (_result_);
			_g_object_unref0 (fd_list);
			_g_object_unref0 (b);
			goto __catch19_g_error;
		}
		self->priv->logind_inhibit_fd = _tmp44_;
		_g_variant_unref0 (_result_);
		_g_object_unref0 (fd_list);
		_g_object_unref0 (b);
	}
	goto __finally19;
	__catch19_g_error:
	{
		GError* e = NULL;
		GError* _tmp48_ = NULL;
		const gchar* _tmp49_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp48_ = e;
		_tmp49_ = _tmp48_->message;
		g_warning ("settings-daemon.vala:138: Failed to inhibit power keys: %s", _tmp49_);
		_g_error_free0 (e);
	}
	__finally19:
	if (_inner_error_ != NULL) {
		enabled = (_vala_array_free (enabled, enabled_length1, (GDestroyNotify) g_free), NULL);
		disabled = (_vala_array_free (disabled, disabled_length1, (GDestroyNotify) g_free), NULL);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	enabled = (_vala_array_free (enabled, enabled_length1, (GDestroyNotify) g_free), NULL);
	disabled = (_vala_array_free (disabled, disabled_length1, (GDestroyNotify) g_free), NULL);
}


static gpointer _g_settings_schema_source_ref0 (gpointer self) {
	return self ? g_settings_schema_source_ref (self) : NULL;
}


static void settings_daemon_set_plugin_enabled (SettingsDaemon* self, const gchar* schema_name, gboolean enabled) {
	GSettingsSchemaSource* source = NULL;
	GSettingsSchemaSource* _tmp0_ = NULL;
	GSettingsSchemaSource* _tmp1_ = NULL;
	GSettingsSchema* schema = NULL;
	GSettingsSchemaSource* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GSettingsSchema* _tmp4_ = NULL;
	GSettingsSchema* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (schema_name != NULL);
	_tmp0_ = g_settings_schema_source_get_default ();
	_tmp1_ = _g_settings_schema_source_ref0 (_tmp0_);
	source = _tmp1_;
	_tmp2_ = source;
	_tmp3_ = schema_name;
	_tmp4_ = g_settings_schema_source_lookup (_tmp2_, _tmp3_, FALSE);
	schema = _tmp4_;
	_tmp5_ = schema;
	if (_tmp5_ != NULL) {
		GSettings* settings = NULL;
		const gchar* _tmp6_ = NULL;
		GSettings* _tmp7_ = NULL;
		GSettings* _tmp8_ = NULL;
		gboolean _tmp9_ = FALSE;
		_tmp6_ = schema_name;
		_tmp7_ = g_settings_new (_tmp6_);
		settings = _tmp7_;
		_tmp8_ = settings;
		_tmp9_ = enabled;
		g_settings_set_boolean (_tmp8_, "active", _tmp9_);
		_g_object_unref0 (settings);
	}
	_g_settings_schema_unref0 (schema);
	_g_settings_schema_source_unref0 (source);
}


static void settings_daemon_start_settings_daemon (SettingsDaemon* self) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->n_names;
	self->priv->n_names = _tmp0_ - 1;
	_tmp1_ = self->priv->n_names;
	if (_tmp1_ != 0) {
		return;
	}
	g_debug ("settings-daemon.vala:159: All bus names acquired, starting unity-setti" \
"ngs-daemon");
	{
		g_spawn_command_line_async (USD_BINARY, &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_SPAWN_ERROR) {
				goto __catch20_g_spawn_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally20;
	__catch20_g_spawn_error:
	{
		GError* e = NULL;
		GError* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = e;
		_tmp3_ = _tmp2_->message;
		g_debug ("settings-daemon.vala:167: Could not start unity-settings-daemon: %s", _tmp3_);
		_g_error_free0 (e);
	}
	__finally20:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


SettingsDaemon* settings_daemon_construct (GType object_type) {
	SettingsDaemon * self = NULL;
	self = (SettingsDaemon*) g_object_new (object_type, NULL);
	return self;
}


SettingsDaemon* settings_daemon_new (void) {
	return settings_daemon_construct (TYPE_SETTINGS_DAEMON);
}


static void settings_daemon_class_init (SettingsDaemonClass * klass) {
	settings_daemon_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SettingsDaemonPrivate));
	G_OBJECT_CLASS (klass)->finalize = settings_daemon_finalize;
}


static void settings_daemon_instance_init (SettingsDaemon * self) {
	self->priv = SETTINGS_DAEMON_GET_PRIVATE (self);
	self->priv->logind_inhibit_fd = -1;
	self->priv->n_names = 0;
}


static void settings_daemon_finalize (GObject* obj) {
	SettingsDaemon * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SETTINGS_DAEMON, SettingsDaemon);
	_g_object_unref0 (self->priv->screen_saver);
	_g_object_unref0 (self->priv->session_manager);
	G_OBJECT_CLASS (settings_daemon_parent_class)->finalize (obj);
}


GType settings_daemon_get_type (void) {
	static volatile gsize settings_daemon_type_id__volatile = 0;
	if (g_once_init_enter (&settings_daemon_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SettingsDaemonClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) settings_daemon_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SettingsDaemon), 0, (GInstanceInitFunc) settings_daemon_instance_init, NULL };
		GType settings_daemon_type_id;
		settings_daemon_type_id = g_type_register_static (G_TYPE_OBJECT, "SettingsDaemon", &g_define_type_info, 0);
		g_once_init_leave (&settings_daemon_type_id__volatile, settings_daemon_type_id);
	}
	return settings_daemon_type_id__volatile;
}


ScreenSaverInterface* screen_saver_interface_construct (GType object_type) {
	ScreenSaverInterface * self = NULL;
	GnomeIdleMonitor* _tmp0_ = NULL;
	self = (ScreenSaverInterface*) g_object_new (object_type, NULL);
	_tmp0_ = gnome_idle_monitor_new ();
	_g_object_unref0 (self->priv->idle_monitor);
	self->priv->idle_monitor = _tmp0_;
	_screen_saver_interface_set_active (self, FALSE);
	return self;
}


ScreenSaverInterface* screen_saver_interface_new (void) {
	return screen_saver_interface_construct (TYPE_SCREEN_SAVER_INTERFACE);
}


static void ___lambda7_ (ScreenSaverInterface* self) {
	screen_saver_interface_set_active (self, FALSE);
}


static void ____lambda7__gnome_idle_monitor_watch_func (GnomeIdleMonitor* monitor, guint id, gpointer self) {
	___lambda7_ (self);
}


static void ____lambda8_ (ScreenSaverInterface* self) {
	screen_saver_interface_set_active (self, TRUE);
}


static void _____lambda8__gnome_idle_monitor_watch_func (GnomeIdleMonitor* monitor, guint id, gpointer self) {
	____lambda8_ (self);
}


static void _screen_saver_interface_set_active (ScreenSaverInterface* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	guint _tmp1_ = 0U;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_active = _tmp0_;
	_tmp1_ = self->priv->idle_watch;
	if (_tmp1_ != ((guint) 0)) {
		GnomeIdleMonitor* _tmp2_ = NULL;
		guint _tmp3_ = 0U;
		_tmp2_ = self->priv->idle_monitor;
		_tmp3_ = self->priv->idle_watch;
		gnome_idle_monitor_remove_watch (_tmp2_, _tmp3_);
	}
	self->priv->idle_watch = (guint) 0;
	_tmp4_ = value;
	if (_tmp4_) {
		GnomeIdleMonitor* _tmp5_ = NULL;
		_tmp5_ = self->priv->idle_monitor;
		gnome_idle_monitor_add_user_active_watch (_tmp5_, ____lambda7__gnome_idle_monitor_watch_func, self, NULL);
	} else {
		gint timeout = 0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = ug_settings_get_integer (UG_SETTINGS_KEY_IDLE_TIMEOUT);
		timeout = _tmp6_;
		_tmp7_ = timeout;
		if (_tmp7_ > 0) {
			GnomeIdleMonitor* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			guint _tmp10_ = 0U;
			_tmp8_ = self->priv->idle_monitor;
			_tmp9_ = timeout;
			_tmp10_ = gnome_idle_monitor_add_idle_watch (_tmp8_, (guint64) (_tmp9_ * 1000), _____lambda8__gnome_idle_monitor_watch_func, self, NULL);
			self->priv->idle_watch = _tmp10_;
		}
	}
}


void screen_saver_interface_set_active (ScreenSaverInterface* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_active;
	_tmp1_ = value;
	if (_tmp0_ == _tmp1_) {
		return;
	}
	_tmp2_ = value;
	if (_tmp2_) {
		g_debug ("settings-daemon.vala:209: Screensaver activated");
	} else {
		g_debug ("settings-daemon.vala:211: Screensaver disabled");
	}
	_tmp3_ = value;
	_screen_saver_interface_set_active (self, _tmp3_);
	_tmp4_ = value;
	g_signal_emit_by_name (self, "active-changed", _tmp4_);
}


gboolean screen_saver_interface_get_active (ScreenSaverInterface* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_active;
	result = _tmp0_;
	return result;
}


guint32 screen_saver_interface_get_active_time (ScreenSaverInterface* self) {
	guint32 result = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	result = (guint32) 0;
	return result;
}


void screen_saver_interface_lock (ScreenSaverInterface* self) {
	g_return_if_fail (self != NULL);
}


void screen_saver_interface_show_message (ScreenSaverInterface* self, const gchar* summary, const gchar* body, const gchar* icon) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (summary != NULL);
	g_return_if_fail (body != NULL);
	g_return_if_fail (icon != NULL);
}


void screen_saver_interface_simulate_user_activity (ScreenSaverInterface* self) {
	g_return_if_fail (self != NULL);
}


static void screen_saver_interface_class_init (ScreenSaverInterfaceClass * klass) {
	screen_saver_interface_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ScreenSaverInterfacePrivate));
	G_OBJECT_CLASS (klass)->finalize = screen_saver_interface_finalize;
	g_signal_new ("active_changed", TYPE_SCREEN_SAVER_INTERFACE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
}


static void screen_saver_interface_instance_init (ScreenSaverInterface * self) {
	self->priv = SCREEN_SAVER_INTERFACE_GET_PRIVATE (self);
	self->priv->_active = FALSE;
	self->priv->idle_watch = (guint) 0;
}


static void screen_saver_interface_finalize (GObject* obj) {
	ScreenSaverInterface * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SCREEN_SAVER_INTERFACE, ScreenSaverInterface);
	_g_object_unref0 (self->priv->idle_monitor);
	G_OBJECT_CLASS (screen_saver_interface_parent_class)->finalize (obj);
}


GType screen_saver_interface_get_type (void) {
	static volatile gsize screen_saver_interface_type_id__volatile = 0;
	if (g_once_init_enter (&screen_saver_interface_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ScreenSaverInterfaceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) screen_saver_interface_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ScreenSaverInterface), 0, (GInstanceInitFunc) screen_saver_interface_instance_init, NULL };
		GType screen_saver_interface_type_id;
		screen_saver_interface_type_id = g_type_register_static (G_TYPE_OBJECT, "ScreenSaverInterface", &g_define_type_info, 0);
		g_type_set_qdata (screen_saver_interface_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) screen_saver_interface_register_object);
		g_once_init_leave (&screen_saver_interface_type_id__volatile, screen_saver_interface_type_id);
	}
	return screen_saver_interface_type_id__volatile;
}


static void _dbus_screen_saver_interface_set_active (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gboolean value = FALSE;
	GVariant* _tmp214_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp214_ = g_variant_iter_next_value (&_arguments_iter);
	value = g_variant_get_boolean (_tmp214_);
	g_variant_unref (_tmp214_);
	screen_saver_interface_set_active (self, value);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_screen_saver_interface_get_active (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gboolean result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = screen_saver_interface_get_active (self);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_boolean (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_screen_saver_interface_get_active_time (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	guint32 result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = screen_saver_interface_get_active_time (self);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_uint32 (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_screen_saver_interface_lock (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	screen_saver_interface_lock (self);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_screen_saver_interface_show_message (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* summary = NULL;
	GVariant* _tmp215_;
	gchar* body = NULL;
	GVariant* _tmp216_;
	gchar* icon = NULL;
	GVariant* _tmp217_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp215_ = g_variant_iter_next_value (&_arguments_iter);
	summary = g_variant_dup_string (_tmp215_, NULL);
	g_variant_unref (_tmp215_);
	_tmp216_ = g_variant_iter_next_value (&_arguments_iter);
	body = g_variant_dup_string (_tmp216_, NULL);
	g_variant_unref (_tmp216_);
	_tmp217_ = g_variant_iter_next_value (&_arguments_iter);
	icon = g_variant_dup_string (_tmp217_, NULL);
	g_variant_unref (_tmp217_);
	screen_saver_interface_show_message (self, summary, body, icon);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (summary);
	_g_free0 (body);
	_g_free0 (icon);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_screen_saver_interface_simulate_user_activity (ScreenSaverInterface* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	screen_saver_interface_simulate_user_activity (self);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void screen_saver_interface_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "SetActive") == 0) {
		_dbus_screen_saver_interface_set_active (object, parameters, invocation);
	} else if (strcmp (method_name, "GetActive") == 0) {
		_dbus_screen_saver_interface_get_active (object, parameters, invocation);
	} else if (strcmp (method_name, "GetActiveTime") == 0) {
		_dbus_screen_saver_interface_get_active_time (object, parameters, invocation);
	} else if (strcmp (method_name, "Lock") == 0) {
		_dbus_screen_saver_interface_lock (object, parameters, invocation);
	} else if (strcmp (method_name, "ShowMessage") == 0) {
		_dbus_screen_saver_interface_show_message (object, parameters, invocation);
	} else if (strcmp (method_name, "SimulateUserActivity") == 0) {
		_dbus_screen_saver_interface_simulate_user_activity (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* screen_saver_interface_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean screen_saver_interface_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


static void _dbus_screen_saver_interface_active_changed (GObject* _sender, gboolean value, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_boolean (value));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gnome.ScreenSaver", "ActiveChanged", _arguments, NULL);
}


guint screen_saver_interface_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_screen_saver_interface_dbus_interface_info), &_screen_saver_interface_dbus_interface_vtable, data, _screen_saver_interface_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "active-changed", (GCallback) _dbus_screen_saver_interface_active_changed, data);
	return result;
}


static void _screen_saver_interface_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_signal_handlers_disconnect_by_func (data[0], _dbus_screen_saver_interface_active_changed, data);
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


SessionManagerInterface* session_manager_interface_construct (GType object_type) {
	SessionManagerInterface * self = NULL;
	self = (SessionManagerInterface*) g_object_new (object_type, NULL);
	return self;
}


SessionManagerInterface* session_manager_interface_new (void) {
	return session_manager_interface_construct (TYPE_SESSION_MANAGER_INTERFACE);
}


gboolean session_manager_interface_get_session_is_active (SessionManagerInterface* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = TRUE;
	return result;
}


const gchar* session_manager_interface_get_session_name (SessionManagerInterface* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = "ubuntu";
	return result;
}


guint32 session_manager_interface_get_inhibited_actions (SessionManagerInterface* self) {
	guint32 result;
	g_return_val_if_fail (self != NULL, 0U);
	result = (guint32) 0;
	return result;
}


static void session_manager_interface_class_init (SessionManagerInterfaceClass * klass) {
	session_manager_interface_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_session_manager_interface_get_property;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SESSION_MANAGER_INTERFACE_SESSION_IS_ACTIVE, g_param_spec_boolean ("session-is-active", "session-is-active", "session-is-active", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SESSION_MANAGER_INTERFACE_SESSION_NAME, g_param_spec_string ("session-name", "session-name", "session-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SESSION_MANAGER_INTERFACE_INHIBITED_ACTIONS, g_param_spec_uint ("inhibited-actions", "inhibited-actions", "inhibited-actions", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void session_manager_interface_instance_init (SessionManagerInterface * self) {
}


GType session_manager_interface_get_type (void) {
	static volatile gsize session_manager_interface_type_id__volatile = 0;
	if (g_once_init_enter (&session_manager_interface_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SessionManagerInterfaceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) session_manager_interface_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SessionManagerInterface), 0, (GInstanceInitFunc) session_manager_interface_instance_init, NULL };
		GType session_manager_interface_type_id;
		session_manager_interface_type_id = g_type_register_static (G_TYPE_OBJECT, "SessionManagerInterface", &g_define_type_info, 0);
		g_type_set_qdata (session_manager_interface_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) session_manager_interface_register_object);
		g_once_init_leave (&session_manager_interface_type_id__volatile, session_manager_interface_type_id);
	}
	return session_manager_interface_type_id__volatile;
}


static void _vala_session_manager_interface_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SessionManagerInterface * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_SESSION_MANAGER_INTERFACE, SessionManagerInterface);
	switch (property_id) {
		case SESSION_MANAGER_INTERFACE_SESSION_IS_ACTIVE:
		g_value_set_boolean (value, session_manager_interface_get_session_is_active (self));
		break;
		case SESSION_MANAGER_INTERFACE_SESSION_NAME:
		g_value_set_string (value, session_manager_interface_get_session_name (self));
		break;
		case SESSION_MANAGER_INTERFACE_INHIBITED_ACTIONS:
		g_value_set_uint (value, session_manager_interface_get_inhibited_actions (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void session_manager_interface_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	g_object_unref (invocation);
}


static GVariant* _dbus_session_manager_interface_get_session_is_active (SessionManagerInterface* self) {
	gboolean result;
	GVariant* _reply;
	result = session_manager_interface_get_session_is_active (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_session_manager_interface_get_session_name (SessionManagerInterface* self) {
	const gchar* result;
	GVariant* _reply;
	result = session_manager_interface_get_session_name (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_session_manager_interface_get_inhibited_actions (SessionManagerInterface* self) {
	guint32 result;
	GVariant* _reply;
	result = session_manager_interface_get_inhibited_actions (self);
	_reply = g_variant_new_uint32 (result);
	return _reply;
}


static GVariant* session_manager_interface_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "SessionIsActive") == 0) {
		return _dbus_session_manager_interface_get_session_is_active (object);
	} else if (strcmp (property_name, "SessionName") == 0) {
		return _dbus_session_manager_interface_get_session_name (object);
	} else if (strcmp (property_name, "InhibitedActions") == 0) {
		return _dbus_session_manager_interface_get_inhibited_actions (object);
	}
	return NULL;
}


static gboolean session_manager_interface_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint session_manager_interface_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_session_manager_interface_dbus_interface_info), &_session_manager_interface_dbus_interface_vtable, data, _session_manager_interface_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _session_manager_interface_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



